const DEFAULT_USER_STRUCTURE = {
    "prefix": "&",
    "status": "dnd",
    "langue": "fr",
    "time": 60000,
    "theme": "default",
    "emoji": "🚩",
    "noaddgrp": false,
    "noaddgrptext": null,
    "twitch": "https://twitch.tv/talmo",
    "rpconoff": true,
    "rpctitle": "Reddom, Best $elfbot",
    "rpcdetails": "Reddom on top",
    "rpcstate": "✦",
    "rpctype": "COMPETING",
    "rpclargeimage": "https://media.discordapp.net/external/7qjxr257hbSkr7If4Q48WoqQ80xztYxhiDdrrXZNFPQ/https/i.postimg.cc/HL4rP2VD/image.png",
    "rpclargeimagetext": ".gg/reddom",
    "rpcsmallimage": "",
    "rpcsmallimagetext": null,
    "appid": "1277327736050024562",
    "buttontext1": "",
    "buttonlink1": "",
    "buttontext2": null,
    "buttonlink2": null,
    "rpctime": "2025-02-19T21:40:44.146Z",
    "rpcminparty": 1,
    "rpcmaxparty": 5,
    "streaming": null,
    "webhooklogs": null,
    "voiceconnect": "",
    "voicemute": false,
    "voicedeaf": false,
    "voicewebcam": true,
    "voicestream": false,
    "spotifyonoff": "off",
    "spotifylargeimage": "",
    "spotifysmallimage": "",
    "spotifysongname": "",
    "spotifyartists": "",
    "spotifyalbumname": "",
    "spotifyendtimestamp": null,
    "spotifysongid": "",
    "spotifyalbumid": "",
    "spotifyartistids": [],
    "spotifystates": "",
    "botname": "Red Dom",
    "rpcplatform": "desktop",
    "afk": null,
    "afkmessage": null,
    "afkwebhook": null,
    "clear": false,
    "clearDelay": null
};

module.exports = {
    DEFAULT_USER_STRUCTURE
};