const axios = require("axios");
const { language } = require("../../fonctions");

const cityTimezones = {
    "Paris": "Europe/Paris",
    "Londres": "Europe/London",
    "Berlin": "Europe/Berlin",
    "Madrid": "Europe/Madrid",
    "Rome": "Europe/Rome",
    "Bruxelles": "Europe/Brussels",
    "Amsterdam": "Europe/Amsterdam",
    "Lisbonne": "Europe/Lisbon",
    "Vienne": "Europe/Vienna",
    "Copenhague": "Europe/Copenhagen",
    "Stockholm": "Europe/Stockholm",
    "Oslo": "Europe/Oslo",
    "Helsinki": "Europe/Helsinki",
    "Prague": "Europe/Prague",
    "Budapest": "Europe/Budapest",
    "Sofia": "Europe/Sofia",
    "Zagreb": "Europe/Zagreb",
    "Athènes": "Europe/Athens",
    "Tallinn": "Europe/Tallinn",
    "Riga": "Europe/Riga",
    "Vilnius": "Europe/Vilnius",
    "Sarajevo": "Europe/Sarajevo",
    "Podgorica": "Europe/Podgorica",
    "Tirana": "Europe/Tirana",
    "Bratislava": "Europe/Bratislava",
    "La Valette": "Europe/Valletta",
    "Minsk": "Europe/Minsk",
    "Dublin": "Europe/Dublin",
    "Luxembourg": "Europe/Luxembourg",
    "Monaco": "Europe/Monaco",
    "San Marin": "Europe/San_Marino",
    "Andorre": "Europe/Andorra",
    "Chisinau": "Europe/Chisinau",
    "Kiev": "Europe/Kiev",
    "Dubrovnik": "Europe/Zagreb",
    "Lille": "Europe/Paris",
    "Nantes": "Europe/Paris",
    "Marseille": "Europe/Paris",
    "Nice": "Europe/Paris",
    "Lyon": "Europe/Paris",
    "Turin": "Europe/Rome",
    "Gênes": "Europe/Rome",
    "Bologne": "Europe/Rome",
    "Florence": "Europe/Rome",
    "Vérone": "Europe/Rome",
    "Trieste": "Europe/Rome",
    "Ravenne": "Europe/Rome",
    "Milan": "Europe/Rome",
    "Venise": "Europe/Rome",
    "Bari": "Europe/Rome",
    "Bergame": "Europe/Rome",
    "Catane": "Europe/Rome",
    "Bucarest": "Europe/Bucharest",
    "Québec": "America/Toronto",
    "Belgrade": "Europe/Belgrade",
    "Sofia": "Europe/Sofia",
    "Zagreb": "Europe/Zagreb",
    "Sarajevo": "Europe/Sarajevo",
    "Ljubljana": "Europe/Ljubljana",
    "Bratislava": "Europe/Bratislava",
    "Krakow": "Europe/Warsaw",
    "Varsovie": "Europe/Warsaw",
    "Vilnius": "Europe/Vilnius",
    "Riga": "Europe/Riga",
    "Tallinn": "Europe/Tallinn",
    "Helsinki": "Europe/Helsinki",
    "Oslo": "Europe/Oslo",
    "Stockholm": "Europe/Stockholm",
    "Copenhague": "Europe/Copenhagen",
    "Amsterdam": "Europe/Amsterdam",
    "Bruxelles": "Europe/Brussels",
    "Luxembourg": "Europe/Luxembourg",
    "Monaco": "Europe/Monaco",
    "Andorre": "Europe/Andorra",
    "San Marin": "Europe/San_Marino",
    "Tbilissi": "Asia/Tbilisi",
    "Yerevan": "Asia/Yerevan",
    "Tiraspol": "Europe/Tiraspol",
    "Chisinau": "Europe/Chisinau",
    "Minsk": "Europe/Minsk",
    "Sofia": "Europe/Sofia",
    "Athènes": "Europe/Athens",
    "Sofia": "Europe/Sofia",
    "Tirana": "Europe/Tirana",
    "Kiev": "Europe/Kiev",
    "Nicosie": "Asia/Nicosia",
  
    "Le Caire": "Africa/Cairo",
    "Lagos": "Africa/Lagos",
    "Nairobi": "Africa/Nairobi",
    "Johannesbourg": "Africa/Johannesburg",
    "Kinshasa": "Africa/Kinshasa",
    "Addis-Abeba": "Africa/Addis_Ababa",
    "Dar es Salaam": "Africa/Dar_es_Salaam",
    "Khartoum": "Africa/Khartoum",
    "Abidjan": "Africa/Abidjan",
    "Accra": "Africa/Accra",
    "Alger": "Africa/Algiers",
    "Casablanca": "Africa/Casablanca",
    "Cape Town": "Africa/Johannesburg",
    "Luanda": "Africa/Luanda",
    "Harcourt": "Africa/Lagos",
    "Kigali": "Africa/Kigali",
    "Lomé": "Africa/Lome",
    "N'Djamena": "Africa/Ndjamena",
    "Bamako": "Africa/Bamako",
    "Cotonou": "Africa/Porto-Novo",
    "Brazzaville": "Africa/Brazzaville",
    "Ouagadougou": "Africa/Ouagadougou",
    "Port Harcourt": "Africa/Lagos",
    "Yaoundé": "Africa/Douala",
    "Lagos": "Africa/Lagos",
    "Antananarivo": "Indian/Antananarivo",
    "Mogadiscio": "Africa/Mogadishu",
    "Niamey": "Africa/Niamey",
    "Djibouti": "Africa/Djibouti",
    "Maputo": "Africa/Maputo",
    "Freetown": "Africa/Freetown",
    "Sierra Leone": "Africa/Freetown",
    "Dakar": "Africa/Dakar",
    "Nairobi": "Africa/Nairobi",
    "Juba": "Africa/Juba",
    "Lomé": "Africa/Lome",
    "Kampala": "Africa/Kampala",
    "Gitega": "Africa/Bujumbura",
    "Bujumbura": "Africa/Bujumbura",
    "Bujumbura": "Africa/Bujumbura",
    "Kisumu": "Africa/Nairobi",
    "Gaborone": "Africa/Gaborone",
    "Windhoek": "Africa/Windhoek",
    "Sofala": "Africa/Maputo",
    "Lusaka": "Africa/Lusaka",
    "Lilongwe": "Africa/Lilongwe",
    "Harare": "Africa/Harare",
    "Blantyre": "Africa/Lilongwe",
    "Antananarivo": "Indian/Antananarivo",
    "Maseru": "Africa/Maseru",
    "Maseru": "Africa/Maseru",
    "Mbabane": "Africa/Mbabane",
    "Helsinki": "Africa/Nairobi",
    "Juba": "Africa/Juba",
    "Malabo": "Africa/Malabo",
    "Nairobi": "Africa/Nairobi",
    "Kinshasa": "Africa/Kinshasa",
    "Yamoussoukro": "Africa/Abidjan",
    "Sao Tomé": "Africa/Sao_Tome",
    "Brazzaville": "Africa/Brazzaville",
    "Libreville": "Africa/Libreville",
    "Porto-Novo": "Africa/Porto-Novo",
    "Banjul": "Africa/Banjul",
    "Monrovia": "Africa/Monrovia",
    "Victoria": "Indian/Mahe",
    "Maseru": "Africa/Maseru",
    "Port Louis": "Indian/Mauritius",
    "Antananarivo": "Indian/Antananarivo",
    "Kigali": "Africa/Kigali",
    "Mbabane": "Africa/Mbabane",
    "Nairobi": "Africa/Nairobi",
    "Maputo": "Africa/Maputo",
    "Dakar": "Africa/Dakar",
    "Gaborone": "Africa/Gaborone",
    "Windhoek": "Africa/Windhoek",
    "Lusaka": "Africa/Lusaka",
    "Lilongwe": "Africa/Lilongwe",
    "Harare": "Africa/Harare",
    "Bujumbura": "Africa/Bujumbura",
    "Djibouti": "Africa/Djibouti",
    "Antananarivo": "Indian/Antananarivo",
    "Nairobi": "Africa/Nairobi",
    "Juba": "Africa/Juba",
    "Mogadiscio": "Africa/Mogadishu",
    "Gitega": "Africa/Gitega",
    "Helsinki": "Africa/Nairobi",
    "Nairobi": "Africa/Nairobi",
    "Bujumbura": "Africa/Bujumbura",
    "Porto-Novo": "Africa/Porto-Novo",
    "Lomé": "Africa/Lome",
    "Mombasa": "Africa/Nairobi",
    "Malabo": "Africa/Malabo",
    "Banjul": "Africa/Banjul",
    "Kigali": "Africa/Kigali",
    "Freetown": "Africa/Freetown",
    "Monrovia": "Africa/Monrovia",
    "Conakry": "Africa/Conakry",
    "Lomé": "Africa/Lome",
    "Cotonou": "Africa/Porto-Novo",
    "Gaborone": "Africa/Gaborone",
    "Maputo": "Africa/Maputo",
    "Lusaka": "Africa/Lusaka",
    "Harare": "Africa/Harare",
    "Antananarivo": "Indian/Antananarivo",
    "Porto-Novo": "Africa/Porto-Novo",
    "Maseru": "Africa/Maseru",
    "Djibouti": "Africa/Djibouti",
    "Yaoundé": "Africa/Douala",
    "Libreville": "Africa/Libreville",
    "Nairobi": "Africa/Nairobi",
    "N'Djamena": "Africa/Ndjamena",
    "Bamako": "Africa/Bamako",
    "Bujumbura": "Africa/Bujumbura",
    "Conakry": "Africa/Conakry",
    "Cotonou": "Africa/Porto-Novo",
    "Niamey": "Africa/Niamey",
    "Kigali": "Africa/Kigali",
    "Abuja": "Africa/Lagos",
    "Khartoum": "Africa/Khartoum",
    "Luanda": "Africa/Luanda",
    "Mogadiscio": "Africa/Mogadishu",
    "Banjul": "Africa/Banjul",
    "Lomé": "Africa/Lome",
    "Porto-Novo": "Africa/Porto-Novo",
    "Gaborone": "Africa/Gaborone",
    "Lagos": "Africa/Lagos",
    "Addis-Abeba": "Africa/Addis_Ababa",
    "Nairobi": "Africa/Nairobi",
    "Mombasa": "Africa/Nairobi",
    "Mbeya": "Africa/Dar_es_Salaam",
    "Arusha": "Africa/Dar_es_Salaam",
    "Gisenyi": "Africa/Kigali",
    "Kampala": "Africa/Kampala",
    "Moroni": "Indian/Comoro",
    "Victoria": "Indian/Mahe",
    "Yamoussoukro": "Africa/Abidjan",
    "Malabo": "Africa/Malabo",
    "Bissau": "Africa/Bissau",
    "Conakry": "Africa/Conakry",
    "Freetown": "Africa/Freetown",
    "Monrovia": "Africa/Monrovia",
    "Banjul": "Africa/Banjul",
    "Djibouti": "Africa/Djibouti",
    "Juba": "Africa/Juba",
    "Yamoussoukro": "Africa/Abidjan",
    "Porto-Novo": "Africa/Porto-Novo",
    "Bamako": "Africa/Bamako",
    "Harcourt": "Africa/Lagos",
    "Niamey": "Africa/Niamey",
    "Maputo": "Africa/Maputo",
    "Lilongwe": "Africa/Lilongwe",
    "Gitega": "Africa/Gitega",
    "Kampala": "Africa/Kampala",
    "Nairobi": "Africa/Nairobi",
    "Antananarivo": "Indian/Antananarivo",
    "Helsinki": "Africa/Nairobi",
    "Cotonou": "Africa/Porto-Novo",
    "Lomé": "Africa/Lome",
    "Libreville": "Africa/Libreville",
    "Yaoundé": "Africa/Douala",
    "Mogadiscio": "Africa/Mogadishu",
    "Bujumbura": "Africa/Bujumbura",
    "Freetown": "Africa/Freetown",
    "Monrovia": "Africa/Monrovia",
    "Djibouti": "Africa/Djibouti",
    "Nairobi": "Africa/Nairobi",
    "Maseru": "Africa/Maseru",
    "Mogadiscio": "Africa/Mogadishu",
    "Juba": "Africa/Juba",
    "Banjul": "Africa/Banjul",
    "Conakry": "Africa/Conakry",
    "Porto-Novo": "Africa/Porto-Novo",
    "Abuja": "Africa/Lagos",
    "Nairobi": "Africa/Nairobi",
    "Sao Tomé": "Africa/Sao_Tome",
    "Antananarivo": "Indian/Antananarivo",
    "Djibouti": "Africa/Djibouti",
    "Kinshasa": "Africa/Kinshasa",
    "Mogadiscio": "Africa/Mogadishu",
    "Kigali": "Africa/Kigali",
    "Yaoundé": "Africa/Douala",
    "Blantyre": "Africa/Lilongwe",
    "Maseru": "Africa/Maseru",
    "Banjul": "Africa/Banjul",
    "Gitega": "Africa/Bujumbura",
    "Bamako": "Africa/Bamako",
    "Lomé": "Africa/Lome",
    "Djibouti": "Africa/Djibouti",
    "Lusaka": "Africa/Lusaka",
    "Kigali": "Africa/Kigali",
    "Harare": "Africa/Harare",
    "Bujumbura": "Africa/Bujumbura",
    "Yamoussoukro": "Africa/Abidjan",
    "Victoria": "Indian/Mahe",
    "Malabo": "Africa/Malabo",
    "Gaborone": "Africa/Gaborone",
    "Lilongwe": "Africa/Lilongwe",
    "Maputo": "Africa/Maputo",
    "Nairobi": "Africa/Nairobi",
    "Cotonou": "Africa/Porto-Novo",
    "Abuja": "Africa/Lagos",
    "Harare": "Africa/Harare",
    "Porto-Novo": "Africa/Porto-Novo",
    "Conakry": "Africa/Conakry",
    "Yamoussoukro": "Africa/Abidjan",
    "Lomé": "Africa/Lome",
    "Maseru": "Africa/Maseru",
    "Sao Tomé": "Africa/Sao_Tome",
    "Lomé": "Africa/Lome",
    "Gaborone": "Africa/Gaborone",
    "Harare": "Africa/Harare",
    "Mogadiscio": "Africa/Mogadishu",
    "Djibouti": "Africa/Djibouti",
    "Kinshasa": "Africa/Kinshasa",
    "Juba": "Africa/Juba",
    "Harcourt": "Africa/Lagos",
    "Bamako": "Africa/Bamako",
    "Yaoundé": "Africa/Douala",
    "Antananarivo": "Indian/Antananarivo",
    "Lusaka": "Africa/Lusaka",
    "Maputo": "Africa/Maputo",
    "Mogadiscio": "Africa/Mogadishu",
    "Gitega": "Africa/Bujumbura",
    "Banjul": "Africa/Banjul",
    "Maseru": "Africa/Maseru",
    "Malabo": "Africa/Malabo",
    "Mogadiscio": "Africa/Mogadishu",
    "Kigali": "Africa/Kigali",
    "Sao Tomé": "Africa/Sao_Tome",
    "Djibouti": "Africa/Djibouti",
    "Maseru": "Africa/Maseru",
    "Libreville": "Africa/Libreville",
    "Djibouti": "Africa/Djibouti",
    "Mogadiscio": "Africa/Mogadishu",
    "Freetown": "Africa/Freetown",
    "Banjul": "Africa/Banjul",
    "Nairobi": "Africa/Nairobi",
    "Mogadiscio": "Africa/Mogadishu",
    "Djibouti": "Africa/Djibouti",
    "Freetown": "Africa/Freetown",
    "Conakry": "Africa/Conakry",
    "Maputo": "Africa/Maputo",
    "Lagos": "Africa/Lagos",
    "Accra": "Africa/Accra",
    "Nairobi": "Africa/Nairobi",
    "Juba": "Africa/Juba",
    "Mogadiscio": "Africa/Mogadishu",
    "Lomé": "Africa/Lome",
    "Yamoussoukro": "Africa/Abidjan",
    "Antananarivo": "Indian/Antananarivo",
    "Bamako": "Africa/Bamako",
    "Cotonou": "Africa/Porto-Novo",
    "Lagos": "Africa/Lagos",
    "Gaborone": "Africa/Gaborone",
    "Porto-Novo": "Africa/Porto-Novo",
    "Nairobi": "Africa/Nairobi",
    "Lilongwe": "Africa/Lilongwe",
    "Antananarivo": "Indian/Antananarivo",
    "Sao Tomé": "Africa/Sao_Tome",
    "Malabo": "Africa/Malabo",
    "Kinshasa": "Africa/Kinshasa",
    "Bujumbura": "Africa/Bujumbura",
    "Juba": "Africa/Juba",
    "Maputo": "Africa/Maputo",
    "Lilongwe": "Africa/Lilongwe",
    "Dakar": "Africa/Dakar",
    "Banjul": "Africa/Banjul",
    "Maseru": "Africa/Maseru",
    "Bujumbura": "Africa/Bujumbura",
    "Lomé": "Africa/Lome",
    "Gitega": "Africa/Bujumbura",
    "Monrovia": "Africa/Monrovia",
    "Malabo": "Africa/Malabo",
    "Abuja": "Africa/Lagos",
    "Sao Tomé": "Africa/Sao_Tome",
    "Conakry": "Africa/Conakry",
    "Maputo": "Africa/Maputo",
    "Nairobi": "Africa/Nairobi",
    "Djibouti": "Africa/Djibouti",
    "Nairobi": "Africa/Nairobi",
    "Mombasa": "Africa/Nairobi",
    "Sao Tomé": "Africa/Sao_Tome",
    "Djibouti": "Africa/Djibouti",
    "Mogadiscio": "Africa/Mogadishu",
    "Lagos": "Africa/Lagos",
    "Nairobi": "Africa/Nairobi",
    "Nairobi": "Africa/Nairobi",
    "Djibouti": "Africa/Djibouti",
    "Antananarivo": "Indian/Antananarivo",
    "Lusaka": "Africa/Lusaka",
    "Mombasa": "Africa/Nairobi",
    "Cotonou": "Africa/Porto-Novo",
    "Bujumbura": "Africa/Bujumbura",
    "Accra": "Africa/Accra",
    "Yaoundé": "Africa/Douala",
    "Malabo": "Africa/Malabo",
    "Harcourt": "Africa/Lagos",
    "Djibouti": "Africa/Djibouti",
    "Maputo": "Africa/Maputo",
    "Harare": "Africa/Harare",
    "Freetown": "Africa/Freetown",
    "Kinshasa": "Africa/Kinshasa",
    "Nairobi": "Africa/Nairobi",
    "Malabo": "Africa/Malabo",
    "Djibouti": "Africa/Djibouti",
    "Nairobi": "Africa/Nairobi",
    "Kampala": "Africa/Kampala",
    "Mogadiscio": "Africa/Mogadishu",
    "Harare": "Africa/Harare",
    "Maseru": "Africa/Maseru",
    "Monrovia": "Africa/Monrovia",
    "Nairobi": "Africa/Nairobi",
    "Mombasa": "Africa/Nairobi",
    "Banjul": "Africa/Banjul",
    "Gitega": "Africa/Bujumbura",
    "Bujumbura": "Africa/Bujumbura",
    "Freetown": "Africa/Freetown",
    "Mogadiscio": "Africa/Mogadishu",
    "Antananarivo": "Indian/Antananarivo",
    "Maputo": "Africa/Maputo",
    "Cotonou": "Africa/Porto-Novo",
    "Nairobi": "Africa/Nairobi",
    "Maseru": "Africa/Maseru",
    "Yaoundé": "Africa/Douala",
    "Lagos": "Africa/Lagos",
    "Accra": "Africa/Accra",
    "Djibouti": "Africa/Djibouti",
    "Antananarivo": "Indian/Antananarivo",
    "Lusaka": "Africa/Lusaka",
    "Kigali": "Africa/Kigali",
    "Juba": "Africa/Juba",
    "Djibouti": "Africa/Djibouti",
    "Malabo": "Africa/Malabo",
    "Monrovia": "Africa/Monrovia",
    "Lomé": "Africa/Lome",
    "Bujumbura": "Africa/Bujumbura",
    "Dakar": "Africa/Dakar",
    "Accra": "Africa/Accra",
    "Banjul": "Africa/Banjul",
    "Maputo": "Africa/Maputo",
    "Harare": "Africa/Harare",
    "Nairobi": "Africa/Nairobi",
    "Cotonou": "Africa/Porto-Novo",
    "Maseru": "Africa/Maseru",
    "Yaoundé": "Africa/Douala",
    "Maputo": "Africa/Maputo",
    "Accra": "Africa/Accra",
    "Bamako": "Africa/Bamako",
    "Malabo": "Africa/Malabo",
    "Antananarivo": "Indian/Antananarivo",
    "Lagos": "Africa/Lagos",
    "Nairobi": "Africa/Nairobi",
    "Gaborone": "Africa/Gaborone",
    "Lomé": "Africa/Lome",
    "Bujumbura": "Africa/Bujumbura",
    "Mogadiscio": "Africa/Mogadishu",
    "Gitega": "Africa/Gitega",
    "Bamako": "Africa/Bamako",
    "Freetown": "Africa/Freetown",
    "Yamoussoukro": "Africa/Abidjan",
    "Lagos": "Africa/Lagos",
    "Djibouti": "Africa/Djibouti",
    "Lusaka": "Africa/Lusaka",
    "Antananarivo": "Indian/Antananarivo",
    "Gitega": "Africa/Bujumbura",
    "Maseru": "Africa/Maseru",
    "Conakry": "Africa/Conakry",
    "Maputo": "Africa/Maputo",
    "Yaoundé": "Africa/Douala",
    "Mogadiscio": "Africa/Mogadishu",
    "Kinshasa": "Africa/Kinshasa",
    "Maseru": "Africa/Maseru",
    "Banjul": "Africa/Banjul",
    "Djibouti": "Africa/Djibouti",
    "Lilongwe": "Africa/Lilongwe",
    "Malabo": "Africa/Malabo",
    "Lagos": "Africa/Lagos",
    "Nairobi": "Africa/Nairobi",
    "Harcourt": "Africa/Lagos",
    "Abuja": "Africa/Lagos",
    "Mombasa": "Africa/Nairobi",
    "Yaoundé": "Africa/Douala",
    "Kinshasa": "Africa/Kinshasa",
    "Djibouti": "Africa/Djibouti",
    "Maseru": "Africa/Maseru",
    "Kigali": "Africa/Kigali",
    "Monrovia": "Africa/Monrovia",
    "Freetown": "Africa/Freetown",
    "Kampala": "Africa/Kampala",
    "Gitega": "Africa/Gitega",
    "Dakar": "Africa/Dakar",
    "Accra": "Africa/Accra",
    "Cotonou": "Africa/Porto-Novo",
    "Nairobi": "Africa/Nairobi",
    "Gaborone": "Africa/Gaborone",
    "Harare": "Africa/Harare",
    "Gitega": "Africa/Bujumbura",
    "Mogadiscio": "Africa/Mogadishu",
    "Lusaka": "Africa/Lusaka",
    "Mombasa": "Africa/Nairobi",
    "Lilongwe": "Africa/Lilongwe",
    "Djibouti": "Africa/Djibouti",
    "Maputo": "Africa/Maputo",
    "Nairobi": "Africa/Nairobi",
    "Monrovia": "Africa/Monrovia",
    "Abuja": "Africa/Lagos",
    "Cotonou": "Africa/Porto-Novo",
    "Maseru": "Africa/Maseru",
    "Djibouti": "Africa/Djibouti",
    "Nairobi": "Africa/Nairobi",
    "Freetown": "Africa/Freetown",
    "Lilongwe": "Africa/Lilongwe",
    "Lagos": "Africa/Lagos",
    "Gaborone": "Africa/Gaborone",
    "Malabo": "Africa/Malabo",
    "Mogadiscio": "Africa/Mogadishu",
    "Kinshasa": "Africa/Kinshasa",
    "Dakar": "Africa/Dakar",
    "Nairobi": "Africa/Nairobi",
    "Dakar": "Africa/Dakar",
    "Mogadiscio": "Africa/Mogadishu",
    "Maseru": "Africa/Maseru",
    "Djibouti": "Africa/Djibouti",
    "Antananarivo": "Indian/Antananarivo",
    "Lomé": "Africa/Lome",
    "Yaoundé": "Africa/Douala",
    "Bamako": "Africa/Bamako",
    "Libreville": "Africa/Libreville",
    "Antananarivo": "Indian/Antananarivo",
    "Djibouti": "Africa/Djibouti",
    "Malabo": "Africa/Malabo",
    "Kigali": "Africa/Kigali",
    "Maputo": "Africa/Maputo",
    "Djibouti": "Africa/Djibouti",
    "Freetown": "Africa/Freetown",
    "Kinshasa": "Africa/Kinshasa",
    "Mogadiscio": "Africa/Mogadishu",
    "Accra": "Africa/Accra",
    "Nairobi": "Africa/Nairobi",
    "Monrovia": "Africa/Monrovia",
    "Lagos": "Africa/Lagos",
    "Cotonou": "Africa/Porto-Novo",
    "Gitega": "Africa/Bujumbura",
    "Djibouti": "Africa/Djibouti",
    "Maseru": "Africa/Maseru",
    "Banjul": "Africa/Banjul",
    "Malabo": "Africa/Malabo",
    "Mogadiscio": "Africa/Mogadishu",
    "Lilongwe": "Africa/Lilongwe",
    "Kampala": "Africa/Kampala",
    "Dakar": "Africa/Dakar",
    "Accra": "Africa/Accra",
    "Mombasa": "Africa/Nairobi",
    "Lomé": "Africa/Lome",
    "Djibouti": "Africa/Djibouti",
    "Maseru": "Africa/Maseru",
    "Malabo": "Africa/Malabo",
    "Sao Tomé": "Africa/Sao_Tome",
    "Djibouti": "Africa/Djibouti",
    "Nairobi": "Africa/Nairobi",
    "Antananarivo": "Indian/Antananarivo",
    "Maputo": "Africa/Maputo",
    "Bamako": "Africa/Bamako",
    "Nairobi": "Africa/Nairobi",
    "Lusaka": "Africa/Lusaka",
    "Gitega": "Africa/Gitega",
    "Freetown": "Africa/Freetown",
    "Malabo": "Africa/Malabo",
    "Maseru": "Africa/Maseru",
    "Antananarivo": "Indian/Antananarivo",
    "Banjul": "Africa/Banjul",
    "Djibouti": "Africa/Djibouti",
    "Accra": "Africa/Accra",
    "Djibouti": "Africa/Djibouti",
    "Maputo": "Africa/Maputo",
    "Lagos": "Africa/Lagos",
    "Kinshasa": "Africa/Kinshasa",
    "Sao Tomé": "Africa/Sao_Tome",
    "Bujumbura": "Africa/Bujumbura",
    "Nairobi": "Africa/Nairobi",
    "Monrovia": "Africa/Monrovia",
    "Maseru": "Africa/Maseru",
    "Gitega": "Africa/Bujumbura",
    "Lilongwe": "Africa/Lilongwe",
    "Lagos": "Africa/Lagos",
    "Maputo": "Africa/Maputo",
    "Mombasa": "Africa/Nairobi",
    "Cotonou": "Africa/Porto-Novo",
    "Yaoundé": "Africa/Douala",
    "Gaborone": "Africa/Gaborone",
    "Dakar": "Africa/Dakar",
    "Malabo": "Africa/Malabo",
    "Nairobi": "Africa/Nairobi",
    "Djibouti": "Africa/Djibouti",
    "Djibouti": "Africa/Djibouti",
    "Juba": "Africa/Juba",
    "Dakar": "Africa/Dakar",
    "Nairobi": "Africa/Nairobi",
    "Maseru": "Africa/Maseru",
    "Mombasa": "Africa/Nairobi",
    "Maputo": "Africa/Maputo",
    "Lagos": "Africa/Lagos",
    "Lilongwe": "Africa/Lilongwe",
    "Bamako": "Africa/Bamako",
    "Kigali": "Africa/Kigali",
    "Cotonou": "Africa/Porto-Novo",
    "Malabo": "Africa/Malabo",
    "Djibouti": "Africa/Djibouti",
    "Yaoundé": "Africa/Douala",
    "Freetown": "Africa/Freetown",
    "Nairobi": "Africa/Nairobi",
    "Kigali": "Africa/Kigali",
    "Mogadiscio": "Africa/Mogadishu",
    "Malabo": "Africa/Malabo",
    "Accra": "Africa/Accra",
    "Antananarivo": "Indian/Antananarivo",
    "Djibouti": "Africa/Djibouti",
    "Mombasa": "Africa/Nairobi",
    "Gitega": "Africa/Gitega",
    "Kampala": "Africa/Kampala",
    "Kinshasa": "Africa/Kinshasa",
    "Maputo": "Africa/Maputo",
    "Djibouti": "Africa/Djibouti",
    "Lagos": "Africa/Lagos",
    "Abuja": "Africa/Lagos",
    "Monrovia": "Africa/Monrovia",
    "Yaoundé": "Africa/Douala",
    "Maseru": "Africa/Maseru",
    "Harare": "Africa/Harare",
    "Bujumbura": "Africa/Bujumbura",
    "Juba": "Africa/Juba",
    "Dakar": "Africa/Dakar",
    "Freetown": "Africa/Freetown",
    "Gaborone": "Africa/Gaborone",
    "Cotonou": "Africa/Porto-Novo",
    "Djibouti": "Africa/Djibouti",
    "Lusaka": "Africa/Lusaka",
    "Kigali": "Africa/Kigali",
    "Yaoundé": "Africa/Douala",
    "Lilongwe": "Africa/Lilongwe",
    "Accra": "Africa/Accra",
    "Maseru": "Africa/Maseru",
    "Mogadiscio": "Africa/Mogadishu",
    "Nairobi": "Africa/Nairobi",
    "Monrovia": "Africa/Monrovia",
    "Banjul": "Africa/Banjul",
    "Lagos": "Africa/Lagos",
    "Maputo": "Africa/Maputo",
    "Malabo": "Africa/Malabo",
    "Djibouti": "Africa/Djibouti",
    "Kigali": "Africa/Kigali",
    "Dakar": "Africa/Dakar",
    "Freetown": "Africa/Freetown",
    "Antananarivo": "Indian/Antananarivo",
    "Maputo": "Africa/Maputo",
    "Gitega": "Africa/Bujumbura",
    "Lilongwe": "Africa/Lilongwe",
    "Yaoundé": "Africa/Douala",
    "Nairobi": "Africa/Nairobi",
    "Dakar": "Africa/Dakar",
    "Kigali": "Africa/Kigali",
    "Kinshasa": "Africa/Kinshasa",
    "Malabo": "Africa/Malabo",
    "Juba": "Africa/Juba",
    "Yaoundé": "Africa/Douala",
    "Malabo": "Africa/Malabo",
    "Bamako": "Africa/Bamako",
    "Cotonou": "Africa/Porto-Novo",
    "Antananarivo": "Indian/Antananarivo",
    "Dakar": "Africa/Dakar",
    "Gaborone": "Africa/Gaborone",
    "Mogadiscio": "Africa/Mogadishu",
    "Lusaka": "Africa/Lusaka",
    "Malabo": "Africa/Malabo",
    "Lilongwe": "Africa/Lilongwe",
    "Nairobi": "Africa/Nairobi",
    "Mombasa": "Africa/Nairobi",
    "Djibouti": "Africa/Djibouti",
    "Antananarivo": "Indian/Antananarivo",
    "Gitega": "Africa/Gitega",
    "Maputo": "Africa/Maputo",
    "Gitega": "Africa/Bujumbura",
    "Banjul": "Africa/Banjul",
    "Cotonou": "Africa/Porto-Novo",
    "Bamako": "Africa/Bamako",
    "Djibouti": "Africa/Djibouti",
    "Lagos": "Africa/Lagos",
    "Lusaka": "Africa/Lusaka",
    "Gitega": "Africa/Bujumbura",
    "Kigali": "Africa/Kigali",
    "Monrovia": "Africa/Monrovia",
    "Harare": "Africa/Harare",
    "Djibouti": "Africa/Djibouti",
    "Yaoundé": "Africa/Douala",
    "Mogadiscio": "Africa/Mogadishu",
    "Freetown": "Africa/Freetown",
    "Banjul": "Africa/Banjul",
    "Cotonou": "Africa/Porto-Novo",
    "Nairobi": "Africa/Nairobi",
    "Maputo": "Africa/Maputo",
    "Dakar": "Africa/Dakar",
    "Antananarivo": "Indian/Antananarivo",
    "Maseru": "Africa/Maseru",
    "Maputo": "Africa/Maputo",
    "Mombasa": "Africa/Nairobi",
    "Lusaka": "Africa/Lusaka",
    "Gitega": "Africa/Gitega",
    "Djibouti": "Africa/Djibouti",
    "Maseru": "Africa/Maseru",
    "Nairobi": "Africa/Nairobi",
    "Lagos": "Africa/Lagos",
    "Mogadiscio": "Africa/Mogadishu",
    "Djibouti": "Africa/Djibouti",
    "Mogadiscio": "Africa/Mogadishu",
    "Antananarivo": "Indian/Antananarivo",
    "Djibouti": "Africa/Djibouti",
    "Yaoundé": "Africa/Douala",
    "Freetown": "Africa/Freetown",
    "Kigali": "Africa/Kigali",
    "Maputo": "Africa/Maputo",
    "Bamako": "Africa/Bamako",
    "Nairobi": "Africa/Nairobi",
    "Lagos": "Africa/Lagos",
    "Monrovia": "Africa/Monrovia",
    "Dakar": "Africa/Dakar",
    "Cotonou": "Africa/Porto-Novo",
    "Maseru": "Africa/Maseru",
    "Yaoundé": "Africa/Douala",
    "Lilongwe": "Africa/Lilongwe",
    "Antananarivo": "Indian/Antananarivo",
    "Lagos": "Africa/Lagos",
    "Nairobi": "Africa/Nairobi",
    "Kigali": "Africa/Kigali",
    "Mombasa": "Africa/Nairobi",
    "Kigali": "Africa/Kigali",
    "Maputo": "Africa/Maputo",
    "Gitega": "Africa/Bujumbura",
    "Freetown": "Africa/Freetown",
    "Gaborone": "Africa/Gaborone",
    "Maputo": "Africa/Maputo",
    "Malabo": "Africa/Malabo",
    "Mogadiscio": "Africa/Mogadishu",
    "Djibouti": "Africa/Djibouti",
    "Dakar": "Africa/Dakar",
    "Antananarivo": "Indian/Antananarivo",
    "Accra": "Africa/Accra",
    "Nairobi": "Africa/Nairobi",
    "Yaoundé": "Africa/Douala",
    "Maseru": "Africa/Maseru",
    "Mogadiscio": "Africa/Mogadishu",
    "Freetown": "Africa/Freetown",
    "Mogadiscio": "Africa/Mogadishu",
    "Cotonou": "Africa/Porto-Novo",
    "Malabo": "Africa/Malabo",
    "Dakar": "Africa/Dakar",
    "Maputo": "Africa/Maputo",
    "Lilongwe": "Africa/Lilongwe",
    "Kampala": "Africa/Kampala",
    "Mogadiscio": "Africa/Mogadiscio",
    "Djibouti": "Africa/Djibouti",
    "Yaoundé": "Africa/Douala",
    "Maputo": "Africa/Maputo",
    "Yaoundé": "Africa/Douala",
    "Maseru": "Africa/Maseru",
    "Nairobi": "Africa/Nairobi",
    "Antananarivo": "Indian/Antananarivo",
    "Cotonou": "Africa/Porto-Novo",
    "Nairobi": "Africa/Nairobi",
    "Kigali": "Africa/Kigali",

    "New York": "America/New_York",
    "Los Angeles": "America/Los_Angeles",
    "Chicago": "America/Chicago",
    "Houston": "America/Houston",
    "Toronto": "America/Toronto",
    "Vancouver": "America/Vancouver",
    "Montréal": "America/Toronto",
    "Calgary": "America/Edmonton",
    "Ottawa": "America/Toronto",
    "Chicoutimi": "America/Toronto",
    "Joliette": "America/Toronto",
    "Sao Paulo": "America/Sao_Paulo",
    "Buenos Aires": "America/Argentina/Buenos_Aires",
    "Lima": "America/Lima",
    "Caracas": "America/Caracas",
    "Mexico City": "America/Mexico_City",
    "Bogotá": "America/Bogota",
    "Santiago": "America/Santiago",
    "Quito": "America/Guayaquil",
    "Havana": "America/Havana",
    "San Juan": "America/Puerto_Rico",
    "Asunción": "America/Asuncion",
    "La Paz": "America/La_Paz",
    "Tegucigalpa": "America/Tegucigalpa",
    "Managua": "America/Managua",
    "Kingston": "America/Jamaica",
    "Port-au-Prince": "America/Port-au-Prince",
    "Georgetown": "America/Guyana",
    "Port of Spain": "America/Port_of_Spain",
    "Bridgetown": "America/Barbados",
    "Castries": "America/Castries",
    "Roseau": "America/Roseau",
    "Santa Cruz": "America/Los_Angeles",
    "Cayo": "America/Guatemala",
    "Mérida": "America/Mexico_City",
    "Guadalajara": "America/Mexico_City",
    "Monterrey": "America/Mexico_City",
    "Puebla": "America/Mexico_City",
    "Tijuana": "America/Mexico_City",
    "Saguenay": "America/Toronto",
    "Córdoba": "America/Argentina/Buenos_Aires",
    "Mendoza": "America/Argentina/Buenos_Aires",
    "Salta": "America/Argentina/Buenos_Aires",
    "Rosario": "America/Argentina/Buenos_Aires",
    "Bahía Blanca": "America/Argentina/Buenos_Aires",
    "Córdoba": "America/Argentina/Buenos_Aires",
    "La Plata": "America/Argentina/Buenos_Aires",
    "San Miguel de Tucumán": "America/Argentina/Buenos_Aires",
    "San Salvador": "America/El_Salvador",
    "Quito": "America/Guayaquil",
    "Cuenca": "America/Guayaquil",
    "Guayaquil": "America/Guayaquil",
    "Trujillo": "America/Lima",
    "Piura": "America/Lima",
    "Iquitos": "America/Lima",
    "Arequipa": "America/Lima",
    "Lima": "America/Lima",
    "Santa Cruz de la Sierra": "America/La_Paz",
    "Cochabamba": "America/La_Paz",
    "Sucre": "America/La_Paz",
    "Tarija": "America/La_Paz",
    "La Paz": "America/La_Paz",
    "Tegucigalpa": "America/Tegucigalpa",
    "Managua": "America/Managua",
    "Kingston": "America/Jamaica",
    "Port-au-Prince": "America/Port-au-Prince",
    "Georgetown": "America/Guyana",
    "Port of Spain": "America/Port_of_Spain",
    "Bridgetown": "America/Barbados",
    "Castries": "America/Castries",
    "Roseau": "America/Roseau",
  
    "Tokyo": "Asia/Tokyo",
    "Séoul": "Asia/Seoul",
    "Pékin": "Asia/Shanghai",
    "Dubaï": "Asia/Dubai",
    "Mumbai": "Asia/Kolkata",
    "Bangkok": "Asia/Bangkok",
    "Hanoï": "Asia/Bangkok",
    "Singapour": "Asia/Singapore",
    "Manille": "Asia/Manila",
    "Kuala Lumpur": "Asia/Kuala_Lumpur",
    "Téhéran": "Asia/Tehran",
    "Riyad": "Asia/Riyadh",
    "Beyrouth": "Asia/Beirut",
    "Amman": "Asia/Amman",
    "Damas": "Asia/Damascus",
    "Tachkent": "Asia/Tashkent",
    "Bichkek": "Asia/Bishkek",
    "Nour-Soultan": "Asia/Nur-Sultan",
    "Djakarta": "Asia/Jakarta",
    "Ulaanbaatar": "Asia/Ulaanbaatar",
    "Hanoï": "Asia/Hanoi",
    "Ho Chi Minh-Ville": "Asia/Bangkok",
    "Daiyab": "Asia/Bangkok",
    "Kuala Lumpur": "Asia/Kuala_Lumpur",
    "Malacca": "Asia/Kuala_Lumpur",
    "Penang": "Asia/Kuala_Lumpur",
    "Kuching": "Asia/Kuala_Lumpur",
    "Cébu": "Asia/Manila",
    "Davao": "Asia/Manila",
    "Cagayan de Oro": "Asia/Manila",
    "Zamboanga": "Asia/Manila",
    "Vientiane": "Asia/Vientiane",
    "Luang Prabang": "Asia/Vientiane",
    "Naypyidaw": "Asia/Yangon",
    "Rangoun": "Asia/Yangon",
    "Colombo": "Asia/Colombo",
    "Kandy": "Asia/Colombo",
    "Malé": "Indian/Maldives",
    "Dhaka": "Asia/Dhaka",
    "Chittagong": "Asia/Dhaka",
    "Khulna": "Asia/Dhaka",
    "Sylhet": "Asia/Dhaka",
    "Dacca": "Asia/Dhaka",
    "Thimphou": "Asia/Thimphu",
    "Paro": "Asia/Thimphu",
    "Katmandou": "Asia/Kathmandu",
    "Islamabad": "Asia/Karachi",
    "Lahore": "Asia/Karachi",
    "Karachi": "Asia/Karachi",
    "Srinagar": "Asia/Kolkata",
    "Chandigarh": "Asia/Kolkata",
    "Amritsar": "Asia/Kolkata",
    "Patna": "Asia/Kolkata",
    "Ahmedabad": "Asia/Kolkata",
    "Surat": "Asia/Kolkata",
    "Indore": "Asia/Kolkata",
    "Jaipur": "Asia/Kolkata",
    "Bhopal": "Asia/Kolkata",
    "Lucknow": "Asia/Kolkata",
    "Kanpur": "Asia/Kolkata",
    "Varanasi": "Asia/Kolkata",
    "Agra": "Asia/Kolkata",
    "Jodhpur": "Asia/Kolkata",
    "Jaisalmer": "Asia/Kolkata",
    "Udaipur": "Asia/Kolkata",
    "Aurangabad": "Asia/Kolkata",
    "Nashik": "Asia/Kolkata",
    "Surat": "Asia/Kolkata",
    "Vadodara": "Asia/Kolkata",
    "Thane": "Asia/Kolkata",
    "Nagpur": "Asia/Kolkata",
    "Cochin": "Asia/Kolkata",
    "Visakhapatnam": "Asia/Kolkata",
    "Vijayawada": "Asia/Kolkata",
    "Moscou": "Europe/Moscow",
    "Pyongyang": "Asia/Pyongyang",
  
    "Sydney": "Australia/Sydney",
    "Melbourne": "Australia/Melbourne",
    "Auckland": "Pacific/Auckland",
    "Wellington": "Pacific/Auckland",
    "Brisbane": "Australia/Brisbane",
    "Canberra": "Australia/Canberra",
    "Adélaïde": "Australia/Adelaide",
    "Hobart": "Australia/Hobart",
    "Suva": "Pacific/Fiji",
    "Port Moresby": "Pacific/Port_Moresby",
    "Nouméa": "Pacific/Noumea",
    "Papeete": "Pacific/Tahiti",
    "Apia": "Pacific/Apia",
    "Honiara": "Pacific/Guadalcanal",
    "Port Vila": "Pacific/Efate",
    "Nuku'alofa": "Pacific/Tongatapu",
    "Funafuti": "Pacific/Funafuti",
    "Tarawa": "Pacific/Tarawa",
    "Majuro": "Pacific/Majuro",
    "Kiritimati": "Pacific/Kiritimati",
    "Rarotonga": "Pacific/Rarotonga",
    "Avarua": "Pacific/Rarotonga",
    "Cook Islands": "Pacific/Rarotonga",
    "American Samoa": "Pacific/Pago_Pago",
    "Samoa": "Pacific/Apia",
    "Nauru": "Pacific/Nauru",
    "Tuvalu": "Pacific/Funafuti",
    "Micronésie": "Pacific/Guam",
    "Palau": "Pacific/Palau",
    "Guam": "Pacific/Guam",
    "Wake Island": "Pacific/Wake",
    "Nauru": "Pacific/Nauru",
    "Christmas Island": "Indian/Christmas",
    "Norfolk Island": "Australia/Norfolk",
    "Cocos (Keeling) Islands": "Indian/Christmas",
    "Solomon Islands": "Pacific/Guadalcanal",
    "Vanuatu": "Pacific/Efate",
    "Papua New Guinea": "Pacific/Port_Moresby",
    "Tonga": "Pacific/Tongatapu",
    "Fiji": "Pacific/Fiji",
    "Kiribati": "Pacific/Tarawa",
    "Marshall Islands": "Pacific/Majuro",
    "Samoa": "Pacific/Apia",
    "Solomon Islands": "Pacific/Guadalcanal",
    "New Caledonia": "Pacific/Noumea",
    "Papua New Guinea": "Pacific/Port_Moresby",
    "Niue": "Pacific/Niue",
    "Tokelau": "Pacific/Tokelau",
    "Tuvalu": "Pacific/Funafuti",
    "Vanuatu": "Pacific/Efate",
    "Samoa": "Pacific/Apia",
    "Tonga": "Pacific/Tongatapu",
    "Norfolk Island": "Australia/Norfolk",
    "Macquarie Island": "Australia/Macquarie",
    "Heard Island": "Australia/Heard",
    "Auckland Islands": "Pacific/Auckland",
    "Campbell Island": "Pacific/Auckland",
    "Chatham Islands": "Pacific/Chatham",
    "Kermadec Islands": "Pacific/Kermadec",
    "Bounty Islands": "Pacific/Bounty",
    "Raoul Island": "Pacific/Kermadec",
    "Campbell Island": "Pacific/Auckland",
    "Antipodes Islands": "Pacific/Antipodes",
    "Snares Islands": "Pacific/Snares",
    "Auckland Islands": "Pacific/Auckland",
    "Subantarctic Islands": "Pacific/Subantarctic",
    "Crozet Islands": "Indian/Ocean",
    "Kerguelen Islands": "Indian/Ocean",
    "Bouvet Island": "Antarctica/Bouvet",
    "South Georgia": "Atlantic/South_Georgia",
    "South Sandwich Islands": "Atlantic/South_Sandwich",
    "Heard Island": "Antarctica/Heard",
    "McDonald Islands": "Antarctica/McDonald",
    "King Edward Point": "Antarctica/South_Georgia",
    "Kerguelen Islands": "Indian/Ocean",
    "Crozet Islands": "Indian/Ocean",
    "Bouvet Island": "Antarctica/Bouvet",
};

module.exports = {
  name: "time",
  description: "Affiche l'heure actuelle dans une ville spécifiée",
  run: async (client, message, args) => {
    try {
      if (!args[0]) {
        return message.channel.send(await language(client, 'Tu dois spécifier une ville.', 'You must specify a city.'));
      }

      const city = args.join(" ");
      const timezone = cityTimezones[city];

      if (!timezone) {
        return message.channel.send(await language(client, 'Ville introuvable.', 'City not found.'));
      }
 
      const apiKey = "AL+IrLoXa7rEQ8a3O/LSLA==aMc9HREAeOEVfwFM";  
      const url = `https://api.api-ninjas.com/v1/worldtime?timezone=${encodeURIComponent(timezone)}`;
      
      const response = await axios.get(url, { 
        timeout: 5000,
        headers: {
          'X-Api-Key': apiKey
        }
      });
      
      const data = response.data;
      const currentTime = new Date(data.datetime);
       
      const formattedTime = currentTime.toLocaleString("fr-FR", {
        timeZone: timezone,
        hour: 'numeric',
        minute: 'numeric',
        second: 'numeric',
        hour12: false
      });
 
      const formattedDate = currentTime.toLocaleDateString("fr-FR", {
        timeZone: timezone,
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      });
 
      const daysOfWeek = {
        'Monday': 'Lundi',
        'Tuesday': 'Mardi',
        'Wednesday': 'Mercredi',
        'Thursday': 'Jeudi',
        'Friday': 'Vendredi',
        'Saturday': 'Samedi',
        'Sunday': 'Dimanche'
      };
      
      const dayOfWeekFrench = daysOfWeek[data.day_of_week] || data.day_of_week;

      const infoMessage = await language(client,
        `**Heure actuelle à ${city} : ${formattedTime}**\n` +
        `**Date :** ${formattedDate}\n` +
        `**Fuseau horaire :** ${data.timezone}\n` +
        `**Jour de la semaine :** ${dayOfWeekFrench}`,
        
        `**Current time in ${city}: ${formattedTime}**\n` +
        `**Date:** ${data.date}\n` +
        `**Timezone:** ${data.timezone}\n` +
        `**Day of week:** ${data.day_of_week}`
      );

      await message.channel.send(infoMessage);

    } catch (error) {
      console.error("Erreur lors de l'exécution de la commande time :", error);
      let errorMessage;
      
      if (error.code === 'ECONNABORTED') {
        errorMessage = await language(client, "La requête a expiré. Veuillez réessayer.", "The request timed out. Please try again.");
      } else if (error.response && error.response.status === 401) {
        errorMessage = await language(client, "Erreur : Clé API invalide.", "Error: Invalid API key.");
      } else if (error.response && error.response.status === 404) {
        errorMessage = await language(client, "Erreur : Fuseau horaire non trouvé.", "Error: Timezone not found.");
      } else if (error.response) {
        errorMessage = await language(client, "Erreur : Problème avec l'API (réponse).", "Error: Issue with API response.");
      } else {
        errorMessage = await language(client, "Erreur : Problème avec l'API.", "Error: API issue.");
      }
      
      await message.channel.send(errorMessage);
    }
  }
};