module.exports = {
    name: "langues",
    description: "Affiche toutes les langues disponibles pour la traduction.",
    run: async (client, message) => {
      try {
        const availableLanguages = [
          { code: 'ab', name: 'Abkhaze' },
          { code: 'ace', name: 'Aceh' },
          { code: 'ach', name: 'Acholi' },
          { code: 'af', name: 'Afrikaans' },
          { code: 'sq', name: 'Albanais' },
          { code: 'alz', name: 'Alur' },
          { code: 'am', name: 'Amharique' },
          { code: 'ar', name: 'Arabe' },
          { code: 'hy', name: 'Arménien' },
          { code: 'as', name: 'Assamais' },
          { code: 'awa', name: 'Awadhi' },
          { code: 'ay', name: 'Aymara' },
          { code: 'az', name: 'Azéri' },
          { code: 'ban', name: 'Balinais' },
          { code: 'bm', name: 'Bambara' },
          { code: 'ba', name: 'Bachkir' },
          { code: 'eu', name: 'Basque' },
          { code: 'btx', name: 'Batak Karo' },
          { code: 'bts', name: 'Batak simalungun' },
          { code: 'bbc', name: 'Batak Toba' },
          { code: 'be', name: 'Biélorusse' },
          { code: 'bem', name: 'Bemba' },
          { code: 'bn', name: 'Bengalî' },
          { code: 'bew', name: 'Betawi' },
          { code: 'bho', name: 'Bhodjpouri' },
          { code: 'bik', name: 'Bicol' },
          { code: 'bs', name: 'Bosniaque' },
          { code: 'br', name: 'Breton' },
          { code: 'bg', name: 'Bulgare' },
          { code: 'bua', name: 'Bouriate' },
          { code: 'yue', name: 'Cantonais' },
          { code: 'ca', name: 'Catalan' },
          { code: 'ceb', name: 'Cebuano' },
          { code: 'ny', name: 'Chichewa (Nyanja)' },
          { code: 'zh-CN', name: 'Chinois (simplifié)' },
          { code: 'zh-TW', name: 'Chinois (traditionnel)' },
          { code: 'cv', name: 'Tchouvache' },
          { code: 'co', name: 'Corse' },
          { code: 'crh', name: 'Tatar de Crimée' },
          { code: 'hr', name: 'Croate' },
          { code: 'cs', name: 'Tchèque' },
          { code: 'da', name: 'Danois' },
          { code: 'din', name: 'Dinka' },
          { code: 'dv', name: 'Divehi' },
          { code: 'doi', name: 'Dogri' },
          { code: 'dov', name: 'Dombe' },
          { code: 'nl', name: 'Néerlandais' },
          { code: 'dz', name: 'Dzongkha' },
          { code: 'en', name: 'Anglais' },
          { code: 'eo', name: 'Espéranto' },
          { code: 'et', name: 'Estonien' },
          { code: 'ee', name: 'Éwé' },
          { code: 'fj', name: 'Fidjien' },
          { code: 'fil', name: 'Filipino (Tagalog)' },
          { code: 'fi', name: 'Finnois' },
          { code: 'fr', name: 'Français' },
          { code: 'fr-FR', name: 'Français (français)' },
          { code: 'fr-CA', name: 'Français (canadien)' },
          { code: 'fy', name: 'Frison' },
          { code: 'ff', name: 'Peul' },
          { code: 'gaa', name: 'ga' },
          { code: 'gl', name: 'Galicien' },
          { code: 'lg', name: 'Ganda (Luganda)' },
          { code: 'ka', name: 'Géorgien' },
          { code: 'de', name: 'Allemand' },
          { code: 'el', name: 'Grec' },
          { code: 'gn', name: 'Guarani' },
          { code: 'gu', name: 'Gujarati' },
          { code: 'ht', name: 'Créole haïtien' },
          { code: 'cnh', name: 'Hakha Chin' },
          { code: 'ha', name: 'Haoussa' },
          { code: 'haw', name: 'Hawaïen' },
          { code: 'iw', name: 'Hébreu' },
          { code: 'he', name: 'Hébreu' },
          { code: 'hil', name: 'Hiligaïnon' },
          { code: 'hi', name: 'Hindi' },
          { code: 'hmn', name: 'Hmong' },
          { code: 'hu', name: 'Hongrois' },
          { code: 'hrx', name: 'Hunsrik' },
          { code: 'is', name: 'Islandais' },
          { code: 'ig', name: 'Igbo' },
          { code: 'ilo', name: 'Ilocano' },
          { code: 'id', name: 'Indonésien' },
          { code: 'ga', name: 'Irlandais' },
          { code: 'it', name: 'Italien' },
          { code: 'ja', name: 'Japonais' },
          { code: 'jw', name: 'Javanais' },
          { code: 'jv', name: 'Javanais' },
          { code: 'kn', name: 'Kannara' },
          { code: 'pam', name: 'Pampangan' },
          { code: 'kk', name: 'Kazakh' },
          { code: 'km', name: 'Khmer' },
          { code: 'cgg', name: 'Kiga' },
          { code: 'rw', name: 'Kinyarwanda' },
          { code: 'ktu', name: 'Kituba' },
          { code: 'gom', name: 'Konkani' },
          { code: 'ko', name: 'Coréen' },
          { code: 'kri', name: 'Krio' },
          { code: 'ku', name: 'Kurde (Kurmandji)' },
          { code: 'ckb', name: 'Kurde (Sorani)' },
          { code: 'ky', name: 'Kirghyz' },
          { code: 'lo', name: 'Laotien' },
          { code: 'ltg', name: 'Latgalien' },
          { code: 'la', name: 'Latin' },
          { code: 'lv', name: 'Letton' },
          { code: 'lij', name: 'Ligure' },
          { code: 'li', name: 'Limbourgeois' },
          { code: 'ln', name: 'Lingala' },
          { code: 'lt', name: 'Lituanien' },
          { code: 'lmo', name: 'Lombard' },
          { code: 'luo', name: 'Luo' },
          { code: 'lb', name: 'Luxembourgeois' },
          { code: 'mk', name: 'Macédonien' },
          { code: 'mai', name: 'Maithili' },
          { code: 'mak', name: 'Macassar' },
          { code: 'mg', name: 'Malgache' },
          { code: 'ms', name: 'Malaisien' },
          { code: 'ms-Arab', name: 'Malais (Jawi)' },
          { code: 'ml', name: 'Malayalam' },
          { code: 'mt', name: 'Maltais' },
          { code: 'mi', name: 'Maori' },
          { code: 'mr', name: 'Marathi' },
          { code: 'chm', name: 'Mari des prairies' },
          { code: 'mni-Mtei', name: 'Meitei (Manipuri)' },
          { code: 'min', name: 'Minangkabau' },
          { code: 'lus', name: 'Mizo' },
          { code: 'mn', name: 'Mongol' },
          { code: 'my', name: 'Birman' },
          { code: 'nr', name: 'Ndébélé (Sud)' },
          { code: 'new', name: 'Nepalbhasha (Newari)' },
          { code: 'ne', name: 'Népalais' },
          { code: 'nso', name: 'Sotho du Nord (Sepedi)' },
          { code: 'no', name: 'Norvégien' },
          { code: 'nus', name: 'Nuer' },
          { code: 'oc', name: 'Occitan' },
          { code: 'or', name: 'Odia (Oriya)' },
          { code: 'om', name: 'Oromo' },
          { code: 'pag', name: 'Pangasinan' },
          { code: 'pap', name: 'Papiamento' },
          { code: 'pl', name: 'Polonais' },
          { code: 'pt', name: 'Portugais' },
          { code: 'pa', name: 'Punjabi' },
          { code: 'qu', name: 'Quechua' },
          { code: 'ro', name: 'Roumain' },
          { code: 'rm', name: 'Rhaeto-romance' },
          { code: 'rn', name: 'Rundi' },
          { code: 'ru', name: 'Russe' },
          { code: 'se', name: 'Same (Sami)' },
          { code: 'sr', name: 'Serbe' },
          { code: 'si', name: 'Cingalais' },
          { code: 'sk', name: 'Slovaque' },
          { code: 'sl', name: 'Slovène' },
          { code: 'su', name: 'Sunda' },
          { code: 'sw', name: 'Swahili' },
          { code: 'sv', name: 'Suédois' },
          { code: 'ta', name: 'Tamoul' },
          { code: 'tt', name: 'Tatar' },
          { code: 'te', name: 'Télougou' },
          { code: 'th', name: 'Thaïlandais' },
          { code: 'tr', name: 'Turc' },
          { code: 'tk', name: 'Turkmène' },
          { code: 'uk', name: 'Ukrainien' },
          { code: 'ur', name: 'Ourdou' },
          { code: 'vi', name: 'Vietnamien' },
          { code: 'cy', name: 'Gallois' },
          { code: 'xh', name: 'Xhosa' },
          { code: 'yi', name: 'Yiddish' },
          { code: 'zu', name: 'Zoulou' }
        ];
    
        let languageList1 = availableLanguages.slice(0, 50).map(lang => `${lang.name}: \`${lang.code}\``).join("  |  ");
        let languageList2 = availableLanguages.slice(50, 100).map(lang => `${lang.name}: \`${lang.code}\``).join("  |  ");
        let languageList3 = availableLanguages.slice(100, 168).map(lang => `${lang.name}: \`${lang.code}\``).join("  |  ");
        
        await message.delete()
          
        await message.channel.send(`Liste des langues disponibles pour la traduction :\n${languageList1}`);
    
        await message.channel.send(`${languageList2}`);

        await message.channel.send(`${languageList3}`);
    
      } catch (err) {
        console.error("Erreur lors de l'affichage des langues :", err);
        message.channel.send("Une erreur s'est produite.");
      }
    }
  };
  