const countryCodes = {
    "Afghanistan": "AF",
    "Afrique du Sud": "ZA",
    "Albanie": "AL",
    "Algérie": "DZ",
    "Andorre": "AD",
    "Angola": "AO",
    "Antigua-et-Barbuda": "AG",
    "Arabie Saoudite": "SA",
    "Argentine": "AR",
    "Arménie": "AM",
    "Australie": "AU",
    "Autriche": "AT",
    "Azerbaïdjan": "AZ",
    "Bahamas": "BS",
    "Bahreïn": "BH",
    "Bangladesh": "BD",
    "Barbade": "BB",
    "Bélarus": "BY",
    "Belgique": "BE",
    "Belize": "BZ",
    "Bénin": "BJ",
    "Bhoutan": "BT",
    "Bolivie": "BO",
    "Bosnie-Herzégovine": "BA",
    "Botswana": "BW",
    "Brésil": "BR",
    "Brunei": "BN",
    "Bulgarie": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Bélarus": "BY",
    "Cambodge": "KH",
    "Cameroun": "CM",
    "Canada": "CA",
    "Cap-Vert": "CV",
    "Centrafrique": "CF",
    "Chili": "CL",
    "Chine": "CN",
    "Colombie": "CO",
    "Comores": "KM",
    "Congo": "CG",
    "Congo (République Démocratique du)": "CD",
    "Cook": "CK",
    "Costa Rica": "CR",
    "Croatie": "HR",
    "Cuba": "CU",
    "Danemark": "DK",
    "Djibouti": "DJ",
    "Dominique": "DM",
    "Egypte": "EG",
    "El Salvador": "SV",
    "Equateur": "EC",
    "Érythrée": "ER",
    "Espagne": "ES",
    "Estonie": "EE",
    "Eswatini": "SZ",
    "Etats-Unis": "US",
    "Ethiopie": "ET",
    "Fidji": "FJ",
    "Finlande": "FI",
    "France": "FR",
    "Gabon": "GA",
    "Gambie": "GM",
    "Géorgie": "GE",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Grèce": "GR",
    "Grenade": "GD",
    "Guadeloupe": "GP",
    "Guam": "GU",
    "Guatemala": "GT",
    "Guinée": "GN",
    "Guinée-Bissau": "GW",
    "Guinée équatoriale": "GQ",
    "Guyana": "GY",
    "Haïti": "HT",
    "Honduras": "HN",
    "Hongrie": "HU",
    "Inde": "IN",
    "Indonésie": "ID",
    "Irak": "IQ",
    "Iran": "IR",
    "Irlande": "IE",
    "Islande": "IS",
    "Israël": "IL",
    "Italie": "IT",
    "Jamaïque": "JM",
    "Japon": "JP",
    "Jordanie": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kirghizistan": "KG",
    "Kiribati": "KI",
    "Koweït": "KW",
    "Laos": "LA",
    "Lettonie": "LV",
    "Liban": "LB",
    "Liberia": "LR",
    "Libye": "LY",
    "Liechtenstein": "LI",
    "Lituanie": "LT",
    "Luxembourg": "LU",
    "Madagascar": "MG",
    "Malaisie": "MY",
    "Malawi": "MW",
    "Maldives": "MV",
    "Mali": "ML",
    "Malte": "MT",
    "Maroc": "MA",
    "Marshall": "MH",
    "Maurice": "MU",
    "Mauritanie": "MR",
    "Mexique": "MX",
    "Micronésie": "FM",
    "Moldavie": "MD",
    "Monaco": "MC",
    "Mongolie": "MN",
    "Monténégro": "ME",
    "Mozambique": "MZ",
    "Myanmar": "MM",
    "Namibie": "NA",
    "Nauru": "NR",
    "Népal": "NP",
    "Niger": "NE",
    "Nigeria": "NG",
    "Norvège": "NO",
    "Nouvelle-Calédonie": "NC",
    "Nouvelle-Zélande": "NZ",
    "Oman": "OM",
    "Ouganda": "UG",
    "Ouzbékistan": "UZ",
    "Pakistan": "PK",
    "Palaos": "PW",
    "Panama": "PA",
    "Papouasie-Nouvelle-Guinée": "PG",
    "Paraguay": "PY",
    "Pays-Bas": "NL",
    "Pérou": "PE",
    "Philippines": "PH",
    "Pologne": "PL",
    "Portugal": "PT",
    "Qatar": "QA",
    "République Centrafricaine": "CF",
    "République Dominicaine": "DO",
    "République Tchèque": "CZ",
    "Roumanie": "RO",
    "Royaume-Uni": "GB",
    "Rwanda": "RW",
    "Saint-Christophe-et-Niévès": "KN",
    "Saint-Marin": "SM",
    "Saint-Pierre-et-Miquelon": "PM",
    "Saint-Vincent-et-les-Grenadines": "VC",
    "Sainte-Lucie": "LC",
    "Samoa": "WS",
    "Sao Tomé-et-Principe": "ST",
    "Sénégal": "SN",
    "Serbie": "RS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapour": "SG",
    "Slovaquie": "SK",
    "Slovénie": "SI",
    "Somalie": "SO",
    "Soudan": "SD",
    "Soudan du Sud": "SS",
    "Sri Lanka": "LK",
    "Suède": "SE",
    "Suisse": "CH",
    "Suriname": "SR",
    "Syrie": "SY",
    "Tadjikistan": "TJ",
    "Tanzanie": "TZ",
    "Tchad": "TD",
    "Thaïlande": "TH",
    "Timor-Oriental": "TL",
    "Togo": "TG",
    "Tonga": "TO",
    "Trinité-et-Tobago": "TT",
    "Tunisie": "TN",
    "Turkménistan": "TM",
    "Turquie": "TR",
    "Tuvalu": "TV",
    "Ukraine": "UA",
    "Uruguay": "UY",
    "Vanuatu": "VU",
    "Vatican": "VA",
    "Venezuela": "VE",
    "Viêt Nam": "VN",
    "Yémen": "YE",
    "Zambie": "ZM",
    "Zimbabwe": "ZW"
  };

  const capitalsInFrench = {

    "Afghanistan": "Kaboul",
    "Afrique du Sud": "Pretoria",
    "Albanie": "Tirana",
    "Algérie": "Alger",
    "Andorre": "Andorre-la-Vieille",
    "Angola": "Luanda",
    "Antigua-et-Barbuda": "Saint-John's",
    "Arabie Saoudite": "Riyad",
    "Argentine": "Buenos Aires",
    "Arménie": "Erevan",
    "Australie": "Canberra",
    "Autriche": "Vienne",
    "Azerbaïdjan": "Bakou",
    "Bahamas": "Nassau",
    "Bahreïn": "Manama",
    "Bangladesh": "Dacca",
    "Barbade": "Bridgetown",
    "Belgique": "Bruxelles",
    "Belize": "Belmopan",
    "Bénin": "Porto-Novo",
    "Bhoutan": "Thimphou",
    "Bolivie": "Sucre",
    "Bosnie-Herzégovine": "Sarajevo",
    "Botswana": "Gaborone",
    "Brésil": "Brasilia",
    "Brunei": "Bandar Seri Begawan",
    "Bulgarie": "Sofia",
    "Burkina Faso": "Ouagadougou",
    "Burundi": "Gitega",
    "Cabo Verde": "Praia",
    "Cambodge": "Phnom Penh",
    "Cameroun": "Yaoundé",
    "Canada": "Ottawa",
    "Centrafrique": "Bangui",
    "Chili": "Santiago",
    "Chine": "Pékin",
    "Colombie": "Bogotá",
    "Comores": "Moroni",
    "Congo (Brazzaville)": "Brazzaville",
    "Congo (Kinshasa)": "Kinshasa",
    "Costa Rica": "San José",
    "Croatie": "Zagreb",
    "Cuba": "La Havane",
    "Danemark": "Copenhague",
    "Djibouti": "Djibouti",
    "Dominique": "Roseau",
    "Égypte": "Le Caire",
    "El Salvador": "San Salvador",
    "Équateur": "Quito",
    "Érythrée": "Asmara",
    "Espagne": "Madrid",
    "Estonie": "Tallinn",
    "Eswatini": "Mbabane",
    "États-Unis": "Washington D.C.",
    "Éthiopie": "Addis-Abeba",
    "Fidji": "Suva",
    "Finlande": "Helsinki",
    "France": "Paris",
    "Gabon": "Libreville",
    "Gambie": "Banjul",
    "Géorgie": "Tbilissi",
    "Ghana": "Accra",
    "Gibraltar": "Gibraltar",
    "Grèce": "Athènes",
    "Grenade": "Saint-Georges",
    "Guatemala": "Guatemala",
    "Guinée": "Conakry",
    "Guinée-Bissau": "Bissau",
    "Guyana": "Georgetown",
    "Haïti": "Port-au-Prince",
    "Honduras": "Tegucigalpa",
    "Hongrie": "Budapest",
    "Inde": "New Delhi",
    "Indonésie": "Jakarta",
    "Irak": "Bagdad",
    "Iran": "Téhéran",
    "Irlande": "Dublin",
    "Islande": "Reykjavík",
    "Italie": "Rome",
    "Jamaïque": "Kingston",
    "Japon": "Tokyo",
    "Jordanie": "Amman",
    "Kazakhstan": "Noursoultan",
    "Kenya": "Nairobi",
    "Kirghizistan": "Bichkek",
    "Kiribati": "Tarawa",
    "Koweït": "Koweït",
    "Laos": "Vientiane",
    "Lesotho": "Maseru",
    "Lettonie": "Riga",
    "Liban": "Beyrouth",
    "Liberia": "Monrovia",
    "Libye": "Tripoli",
    "Liechtenstein": "Vaduz",
    "Lituanie": "Vilnius",
    "Luxembourg": "Luxembourg",
    "Madagascar": "Antananarivo",
    "Malaisie": "Kuala Lumpur",
    "Malawi": "Lilongwe",
    "Maldives": "Malé",
    "Mali": "Bamako",
    "Malte": "La Valette",
    "Maroc": "Rabat",
    "Maurice": "Port-Louis",
    "Mauritanie": "Nouakchott",
    "Mexique": "Mexico",
    "Moldavie": "Chisinau",
    "Monaco": "Monaco",
    "Mongolie": "Oulan-Bator",
    "Monténégro": "Podgorica",
    "Maroc": "Rabat",
    "Mozambique": "Maputo",
    "Myanmar": "Naypyidaw",
    "Namibie": "Windhoek",
    "Nauru": "Yaren",
    "Népal": "Katmandou",
    "Niger": "Niamey",
    "Nigéria": "Abuja",
    "Norvège": "Oslo",
    "Nouvelle-Zélande": "Wellington",
    "Nicaragua": "Managua",
    "Niger": "Niamey",
    "Nigeria": "Abuja",
    "Oman": "Mascate",
    "Ouganda": "Kampala",
    "Ouzbékistan": " Tachkent",
    "Pakistan": "Islamabad",
    "Palau": "Ngerulmud",
    "Panama": "Panama",
    "Papouasie-Nouvelle-Guinée": "Port-Moresby",
    "Paraguay": "Asunción",
    "Pays-Bas": "Amsterdam",
    "Pérou": "Lima",
    "Philippines": "Manille",
    "Pologne": "Varsovie",
    "Portugal": "Lisbonne",
    "Qatar": "Doha",
    "République Centrafricaine": "Bangui",
    "République Dominicaine": "Saint-Domingue",
    "République Démocratique du Congo": "Kinshasa",
    "République du Congo": "Brazzaville",
    "Roumanie": "Bucarest",
    "Royaume-Uni": "Londres",
    "Rwanda": "Kigali",
    "Saint-Kitts-et-Nevis": "Basseterre",
    "Saint-Marin": "Saint-Marin",
    "Saint-Siège": "Vatican",
    "Saint-Vincent-et-les-Grenadines": "Kingstown",
    "Sao Tomé-et-Principe": "São Tomé",
    "Sénégal": "Dakar",
    "Serbie": "Belgrade",
    "Seychelles": "Victoria",
    "Sierra Leone": "Freetown",
    "Singapour": "Singapour",
    "Slovaquie": "Bratislava",
    "Slovénie": "Ljubljana",
    "Somalie": "Mogadiscio",
    "Soudan": "Khartoum",
    "Soudan du Sud": "Djouba",
    "Sri Lanka": "Colombo",
    "Suède": "Stockholm",
    "Suisse": "Berne",
    "Syrie": "Damas",
    "Tadjikistan": "Douchanbé",
    "Tanzanie": "Dodoma",
    "Tchad": "N'Djaména",
    "Thaïlande": "Bangkok",
    "Timor-Leste": "Dili",
    "Tunisie": "Tunis",
    "Turkménistan": "Achgabat",
    "Turquie": "Ankara",
    "Tuvalu": "Funafuti",
    "Ukraine": "Kiev",
    "Uruguay": "Montevideo",
    "Vanuatu": "Port-Vila",
    "Vatican": "Vatican",
    "Venezuela": "Caracas",
    "Vietnam": "Hanoï",
    "Yémen": "Sana'a",
    "Zambie": "Lusaka",
    "Zimbabwe": "Harare"
    };
  
  
  const axios = require('axios');
  
  module.exports = {
    name: "capitale",
    description: "Obtenir la capitale d'un pays",
    run: async (client, message, args) => {
      try {
        if (args.length === 0) {
          return message.reply("Veuillez spécifier le nom du pays.");
        }
  
        const countryName = args.join(" ");
        const username = "darkos"; // Remplacez par votre nom d'utilisateur GeoNames
  
        // Vérifiez si le pays existe dans le mapping
        const countryCode = countryCodes[countryName];
        if (!countryCode) {
          return message.reply("Pays non trouvé. Veuillez vérifier l'orthographe.");
        }
  
        // Requête à l'API GeoNames pour obtenir les informations sur le pays
        const response = await axios.get(`http://api.geonames.org/countryInfoJSON?formatted=true&country=${countryCode}&username=${username}`);
        const data = response.data;
  
        if (!data.geonames || data.geonames.length === 0) {
          return message.reply("Pays non trouvé. Veuillez vérifier l'orthographe.");
        }
  
        const country = data.geonames[0];
        const capital = capitalsInFrench[countryName] || country.capital || "Inconnue";
  
        message.reply(`La capitale de **${countryName}** est **${capital}**.`);
      } catch (e) {
        console.error("Erreur lors de la récupération de la capitale", e);
        message.reply("Une erreur est survenue lors de la récupération de la capitale.");
      }
    },
  };