const jokes = [
  "Pourquoi les vampires sont-ils de mauvais médecins ? Parce qu'ils ne pensent qu'à te soutirer du sang.",
  "Qu'est-ce qu'un cimetière dit à l'autre ? 'T'as une place pour moi ?'",
  "Pourquoi Hitler n'aimait pas les énigmes ? Parce qu'il avait du mal à trouver la solution finale.",
  "Comment appelle-t-on un bébé dans un four ? Un petit pain.",
  "Quelle est la différence entre un bébé et un sandwich ? Le sandwich, tu peux le couper sans que ça crie.",
  "Qu'est-ce qui est pire qu'un bébé dans une poubelle ? Un bébé dans deux poubelles.",
  "Pourquoi les bébés ressemblent-ils à des armes ? Parce qu'on les charge, ils partent tout seuls et personne ne sait où ils vont atterrir.",
  "Comment faire sourire un enfant handicapé ? Tu lui envoies une balle dans la bouche.",
  "Quelle est la différence entre une pizza et un juif ? La pizza ne crie pas dans le four.",
  "Comment on appelle un noir qui vole un avion ? Un pilote, raciste de merde.",
  "Qu'est-ce qui est vert et qui pend à un arbre ? Un slip de Schtroumpf.",
  "Comment on fait tenir 100 juifs dans une Coccinelle ? Dans le cendrier.",
  "C'est un aveugle qui traverse la rue. Une femme lui crie : 'Attention, monsieur, un camion !' Il répond : 'T'inquiète, il va me voir.'",
  "Quelle est la différence entre une école et une piscine ? Dans une piscine, les enfants ne crient pas quand tu les mets à l'eau.",
  "Comment on appelle un noir sur un vélo ? Un voleur.",
  "Qu'est-ce qui est pire qu'un enfant mort dans une cave ? Deux enfants morts dans une cave et un seul sandwich.",
  "Pourquoi les bébés sont-ils comme les préservatifs ? Les deux ont 99% de chances d'éviter une grossesse, mais on s'amuse quand même avec.",
  "Comment on appelle une lesbienne noire ? Une voleuse de travail.",
  "Qu'est-ce qui est blanc et qui monte et qui descend ? Un handicapé dans un frigo.",
  "Quelle est la différence entre un juif et une pizza ? La pizza ne crie pas quand tu la mets au four.",
  "Comment on fait cuire un bébé ? Dans une cocotte-minute.",
  "Qu'est-ce qui est pire que de trouver un ver dans sa pomme ? L'Holocauste.",
  "Comment on appelle un noir qui fait du ski ? Un déneigeur.",
  "Quelle est la différence entre un juif et un dessin animé ? Le dessin animé, on peut l'arrêter.",
  "Pourquoi Hitler s'est-il suicidé ? Il a vu la facture de gaz.",
  "Comment on appelle un noir qui vole une banque ? Un braqueur, espèce de raciste.",
  "Qu'est-ce qui est vert, qui monte et qui descend ? Un petit pois dans un ascenseur.",
  "Comment on fait tenir 10 juifs dans une voiture ? Dans une urne.",
  "Quelle est la différence entre un juif et un cadeau de Noël ? Le cadeau, on l'ouvre avant de le jeter.",
  "Pourquoi les noirs ne font-ils pas de blagues ? Parce qu'on leur a déjà pris les bonnes.",
  "Comment on appelle un noir qui sort de l'hôpital ? Un miraculé.",
  "Qu'est-ce qui est pire qu'un bébé mort dans une poubelle ? Un bébé vivant dans une poubelle.",
  "Comment on fait pour qu'un enfant arrête de saigner ? On arrête de le poignarder.",
  "Quelle est la différence entre un juif et une échelle ? L'échelle, on peut la redresser.",
  "Pourquoi les handicapés mentaux sont-ils comme les glaces ? Plus ils fondent, plus ils craquent.",
  "Comment on appelle un noir qui fait du parachute ? Un terroriste.",
  "Qu'est-ce qui est rouge et qui se cache dans un arbre ? Un bébé avec une fourche.",
  "Comment on fait tenir 100 bébés dans un seau ? Avec un mixeur.",
  "Quelle est la différence entre un juif et un vélo ? Le vélo, il ne fait pas de bruit quand tu le mets au four.",
  "Pourquoi les noirs ont-ils les mains blanches ? Parce que quand ils courent, ils se tiennent aux barreaux.",
  "Comment on appelle un noir qui parle avec un autre noir ? Le comité des finances.",
  "Qu'est-ce qui est pire qu'un enfant mort ? Un enfant vivant dans ton placard.",
  "Comment on fait pour qu'un enfant arrête de saigner du nez ? On arrête de lui marcher sur la tête.",
  "Quelle est la différence entre un juif et un sandwich ? Le sandwich, tu peux le partager avec ta famille.",
  "Pourquoi Hitler aimait-il les blagues ? Parce qu'il adorait les chambres à gaz hilarantes.",
  "Comment on appelle un noir qui fait du skate ? Un voleur en fuite.",
  "Qu'est-ce qui est vert et qui saute ? Un petit pois énervé.",
  "Comment on fait tenir 50 juifs dans une boîte d'allumettes ? Normalement, ça rentre.",
  "Quelle est la différence entre un juif et une pizza ? La pizza, tu peux la commander sans anchois.",
  "Pourquoi les bébés sont-ils comme les oignons ? Parce que quand tu les coupes, tu pleures.",
  "Comment on appelle un noir qui fait de la plongée ? Un naufragé.",
  "Qu'est-ce qui est pire qu'un enfant mort dans un frigo ? Deux enfants morts dans un frigo et plus de bière.",
  "Comment on fait pour qu'un enfant arrête de crier ? On lui coupe les cordes vocales.",
  "Quelle est la différence entre un juif et un journal ? Le journal, on peut le lire sans pleurer.",
  "Pourquoi Hitler n'aimait-il pas les jeux vidéo ? Parce qu'il avait du mal à passer le niveau juif.",
  "Comment on appelle un noir qui fait du cheval ? Un jockey, espèce de raciste.",
  "Qu'est-ce qui est rouge et qui fait du bruit ? Un bébé qui joue avec un couteau.",
  "Comment on fait tenir 100 bébés dans une baignoire ? Avec de l'eau et du savon.",
  "Quelle est la différence entre un juif et une chaise ? La chaise, tu peux t'asseoir dessus sans remords.",
  "Pourquoi les handicapés sont-ils comme les avions ? Parce qu'ils font pitié quand ils s'écrasent.",
  "Comment on appelle un noir qui fait de la musculation ? Un voleur de fer.",
  "Qu'est-ce qui est pire qu'un enfant mort dans un micro-ondes ? Un enfant vivant dans un micro-ondes.",
  "Comment on fait pour qu'un enfant arrête de saigner des oreilles ? On arrête de lui crier dessus.",
  "Quelle est la différence entre un juif et un parapluie ? Le parapluie, tu peux l'ouvrir sans qu'il se plaigne.",
  "Pourquoi Hitler aimait-il la nature ? Parce qu'il adorait les camps en plein air.",
  "Comment on appelle un noir qui fait du shopping ? Un suspect.",
  "Qu'est-ce qui est vert et qui pue ? Un bébé oublié au soleil.",
  "Comment on fait tenir 200 juifs dans une voiture ? Dans le réservoir.",
  "Quelle est la différence entre un juif et un ballon ? Le ballon, tu peux le dégonfler sans remords.",
  "Pourquoi les bébés sont-ils comme les cigarettes ? Parce que c'est mauvais pour la santé mais on en fait quand même.",
  "Comment on appelle un noir qui fait du yoga ? Un contorsionniste en prison.",
  "Qu'est-ce qui est pire qu'un enfant mort dans un congélateur ? Un enfant vivant dans un congélateur.",
  "Comment on fait pour qu'un enfant arrête de bouger ? On lui casse les jambes.",
  "Quelle est la différence entre un juif et un téléphone ? Le téléphone, tu peux le raccrocher sans culpabilité.",
  "Pourquoi Hitler n'aimait-il pas les maths ? Parce qu'il avait du mal avec les solutions.",
  "Comment on appelle un noir qui fait de la course ? Un fugitif.",
  "Qu'est-ce qui est rouge et qui monte et qui descend ? Un bébé dans un grille-pain.",
  "Comment on fait tenir 500 bébés dans un stade ? Avec un hachoir.",
  "Quelle est la différence entre un juif et une ampoule ? L'ampoule, tu peux la changer sans problème.",
  "Pourquoi les handicapés sont-ils comme les bonbons ? Plus ils sont mous, plus ils sont faciles à manger.",
  "Comment on appelle un noir qui fait de la peinture ? Un graffeur.",
  "Qu'est-ce qui est pire qu'un enfant mort dans une sécheuse ? Un enfant vivant dans une sécheuse.",
  "Comment on fait pour qu'un enfant arrête de respirer ? On lui met un sac sur la tête.",
  "Quelle est la différence entre un juif et une voiture ? La voiture, tu peux la réparer.",
  "Pourquoi Hitler aimait-il la musique ? Parce qu'il adorait les chambres à gaz en sol majeur.",
  "Comment on appelle un noir qui fait de la menuiserie ? Un voleur de bois.",
  "Qu'est-ce qui est vert et qui saute de joie ? Un bébé qu'on vient d'écraser.",
  "Comment on fait tenir 1000 juifs dans une boîte à chaussures ? En poudre.",
  "Quelle est la différence entre un juif et un livre ? Le livre, tu peux le fermer sans remords.",
  "Pourquoi les bébés sont-ils comme le papier toilette ? Parce que c'est plus fun de les jeter que de les garder.",
  "Comment on appelle un noir qui fait de la magie ? Un illusionniste en prison.",
  "Qu'est-ce qui est pire qu'un enfant mort dans un mixeur ? Un enfant vivant dans un mixeur.",
  "Comment on fait pour qu'un enfant arrête de grandir ? On lui coupe la tête.",
  "Quelle est la différence entre un juif et une télévision ? La télévision, tu peux l'éteindre.",
  "Pourquoi Hitler n'aimait-il pas la plage ? Parce qu'il détestait le sable dans sa solution finale.",
  "Comment on appelle un noir qui fait de la photographie ? Un voleur d'appareil.",
  "Qu'est-ce qui est rouge et qui se balance ? Un bébé sur un crochet.",
  "Comment on fait tenir un million de bébés dans un tiroir ? En purée.",
  "Quelle est la différence entre un juif et un ordinateur ? L'ordinateur, tu peux l'éteindre sans qu'il crie.",
  "Pourquoi les handicapés sont-ils comme les nuages ? Parce que quand ils disparaissent, c'est une belle journée.",
  "Comment on appelle un noir qui fait de la danse ? Un suspect en mouvement.",
  "Qu'est-ce qui est pire qu'un enfant mort dans un lave-vaisselle ? Un enfant vivant dans un lave-vaisselle.",
  "Comment on fait pour qu'un enfant arrête de penser ? On lui enlève le cerveau.",
  "Quelle est la différence entre un juif et un miroir ? Le miroir, tu peux le briser sans conséquence.",
  "Pourquoi Hitler aimait-il l'archéologie ? Parce qu'il adorait les vieux os.",
  "Comment on appelle un noir qui fait de la couture ? Un voleur de fil.",
  "Qu'est-ce qui est vert et qui rit ? Un bébé qu'on vient de jeter du balcon.",
  "Comment on fait tenir tous les juifs du monde dans une pièce ? Avec une porte fermée.",
  "Quelle est la différence entre un juif et une montre ? La montre, tu peux la remonter.",
  "Pourquoi les bébés sont-ils comme les allumettes ? Parce que c'est amusant de les craquer.",
  "Comment on appelle un noir qui fait de la sculpture ? Un voleur de pierre.",
  "Qu'est-ce qui est pire qu'un enfant mort dans un four ? Un enfant vivant dans un four.",
  "Comment on fait pour qu'un enfant arrête de sentir ? On le met dans un cercueil.",
  "Quelle est la différence entre un juif et un stylo ? Le stylo, tu peux le jeter sans remords.",
  "Pourquoi Hitler n'aimait-il pas les énigmes ? Parce qu'il préférait les solutions définitives.",
  "Comment on appelle un noir qui fait de la poterie ? Un voleur d'argile.",
  "Qu'est-ce qui est rouge et qui tourne ? Un bébé dans un micro-ondes.",
  "Comment on fait tenir un bébé dans ta poche ? En morceaux.",
  "Quelle est la différence entre un juif et un puzzle ? Le puzzle, tu peux le terminer.",
  "Pourquoi les handicapés sont-ils comme les feux d'artifice ? Parce que tout le monde regarde quand ils explosent.",
  "Comment on appelle un noir qui fait de la broderie ? Un voleur de tissu.",
  "Qu'est-ce qui est pire qu'un enfant mort dans une machine à laver ? Un enfant vivant dans une machine à laver.",
  "Comment on fait pour qu'un enfant arrête de rêver ? On lui enlève la tête.",
  "Quelle est la différence entre un juif et un livre de coloriage ? Le livre de coloriage, tu peux le colorier sans qu'il saigne.",
  "Pourquoi Hitler aimait-il la chimie ? Parce qu'il adorait les expériences avec le gaz.",
  "Comment on appelle un noir qui fait de la maroquinerie ? Un voleur de cuir.",
  "Qu'est-ce qui est vert et qui n'a pas de jambes ? Un bébé après un accident de voiture.",
  "Comment on fait tenir tous les bébés du monde dans une boîte ? En compote.",
  "Quelle est la différence entre un juif et une radio ? La radio, tu peux changer de station.",
  "Pourquoi les bébés sont-ils comme les bougies ? Parce que c'est plus fun de les souffler que de les regarder.",
  "Comment on appelle un noir qui fait de la sellerie ? Un voleur de selle.",
  "Qu'est-ce qui est pire qu'un enfant mort dans un presse-agrumes ? Un enfant vivant dans un presse-agrumes.",
  "Comment on fait pour qu'un enfant arrête de sentir mauvais ? On le lave à l'acide.",
  "Quelle est la différence entre un juif et un tableau ? Le tableau, tu peux l'accrocher sans problème.",
  "Pourquoi Hitler n'aimait-il pas les devinettes ? Parce qu'il préférait les réponses définitives.",
  "Comment on appelle un noir qui fait de la vannerie ? Un voleur d'osier.",
  "Qu'est-ce qui est rouge et qui danse ? Un bébé sur des charbons ardents.",
  "Comment on fait tenir un bébé dans ton verre ? En smoothie.",
  "Quelle est la différence entre un juif et un jeu vidéo ? Le jeu vidéo, tu peux l'arrêter quand tu veux.",
  "Pourquoi les handicapés sont-ils comme les ballons ? Parce que quand ils éclatent, tout le monde rit.",
  "Comment on appelle un noir qui fait de la spéléologie ? Un prisonnier.",
  "Qu'est-ce qui est pire qu'un enfant mort dans un concasseur ? Un enfant vivant dans un concasseur.",
  "Comment on fait pour qu'un enfant arrête de parler ? On lui coupe la langue.",
  "Quelle est la différence entre un juif et un appareil photo ? L'appareil photo, tu peux le fermer.",
  "Pourquoi Hitler aimait-il la géographie ? Parce qu'il adorait redessiner les frontières.",
  "Comment on appelle un noir qui fait de l'origami ? Un voleur de papier.",
  "Qu'est-ce qui est vert et qui flotte ? Un bébé dans la piscine.",
  "Comment on fait tenir tous les juifs dans ta main ? En cendres.",
  "Quelle est la différence entre un juif et un réveil ? Le réveil, tu peux l'arrêter.",
  "Pourquoi les bébés sont-ils comme le pop-corn ? Parce que c'est plus fun de les faire éclater que de les manger.",
  "Comment on appelle un noir qui fait de la taxidermie ? Un voleur d'animaux.",
  "Qu'est-ce qui est pire qu'un enfant mort dans une centrifugeuse ? Un enfant vivant dans une centrifugeuse.",
  "Comment on fait pour qu'un enfant arrête de voir ? On lui crève les yeux.",
  "Quelle est la différence entre un juif et un dictionnaire ? Le dictionnaire, tu peux le feuilleter.",
  "Pourquoi Hitler n'aimait-il pas les surprises ? Parce qu'il préférait tout planifier.",
  "Comment on appelle un noir qui fait de la reliure ? Un voleur de livres.",
  "Qu'est-ce qui est rouge et qui scintille ? Un bébé couvert de paillettes.",
  "Comment on fait tenir un bébé dans ton assiette ? En steak haché.",
  "Quelle est la différence entre un juif et un calendrier ? Le calendrier, tu peux tourner la page.",
  "Pourquoi les handicapés sont-ils comme les bonbons acidulés ? Parce qu'ils font une drôle de tête quand on les suce.",
  "Comment on appelle un noir qui fait de la dinanderie ? Un voleur de métal.",
  "Qu'est-ce qui est pire qu'un enfant mort dans un broyeur ? Un enfant vivant dans un broyeur.",
  "Comment on fait pour qu'un enfant arrête d'entendre ? On lui perce les tympans.",
  "Quelle est la différence entre un juif et un parapluie ? Le parapluie, tu peux le refermer.",
  "Pourquoi Hitler aimait-il l'histoire ? Parce qu'il adorait réécrire les livres.",
  "Comment on appelle un noir qui fait de la verrerie ? Un voleur de verre.",
  "Qu'est-ce qui est vert et qui saute de building en building ? Un bébé spider-man.",
  "Comment on fait tenir tous les bébés dans un sac ? En farine.",
  "Quelle est la différence entre un juif et un journal ? Le journal, tu peux le jeter.",
  "Pourquoi les bébés sont-ils comme les œufs ? Parce que c'est plus fun de les casser que de les faire éclore.",
  "Comment on appelle un noir qui fait de la céramique ? Un voleur d'argile.",
  "Qu'est-ce qui est pire qu'un enfant mort dans un hachoir ? Un enfant vivant dans un hachoir.",
  "Comment on fait pour qu'un enfant arrête de sentir bon ? On le laisse pourrir.",
  "Quelle est la différence entre un juif et un téléphone portable ? Le téléphone portable, tu peux le éteindre.",
  "Pourquoi Hitler n'aimait-il pas les énigmes ? Parce qu'il préférait les solutions rapides.",
  "Comment on appelle un noir qui fait de l'ébénisterie ? Un voleur de bois.",
  "Qu'est-ce qui est rouge et qui vole ? Un bébé qu'on vient de lancer.",
  "Comment on fait tenir un bébé dans ton verre à shot ? En jus.",
  "Quelle est la différence entre un juif et un livre de recettes ? Le livre de recettes, tu peux le suivre.",
  "Pourquoi les handicapés sont-ils comme les flocons de neige ? Parce que chacun est unique et qu'ils fondent au soleil.",
  "Comment on appelle un noir qui fait de la plumasserie ? Un voleur de plumes.",
  "Qu'est-ce qui est pire qu'un enfant mort dans un mixeur ? Deux enfants morts dans un mixeur et pas assez de place.",
  "Comment on fait pour qu'un enfant arrête de bouger les doigts ? On les coupe.",
  "Quelle est la différence entre un juif et un ordinateur portable ? L'ordinateur portable, tu peux le fermer.",
  "Pourquoi Hitler aimait-il la physique ? Parce qu'il adorait les lois de la gravité.",
  "Comment on appelle un noir qui fait de la tabletterie ? Un voleur d'ivoire.",
  "Qu'est-ce qui est vert et qui n'a pas de bras ? Un bébé après une rencontre avec une tondeuse.",
  "Comment on fait tenir tous les juifs dans une boîte d'allumettes ? En allumettes.",
  "Quelle est la différence entre un juif et un livre audio ? Le livre audio, tu peux l'arrêter.",
  "Pourquoi les bébés sont-ils comme les dominos ? Parce que c'est amusant de les faire tomber.",
  "Comment on appelle un noir qui fait de la glyptique ? Un voleur de pierres précieuses.",
  "Qu'est-ce qui est pire qu'un enfant mort dans un compacteur ? Un enfant vivant dans un compacteur.",
  "Comment on fait pour qu'un enfant arrête de sourire ? On lui casse la mâchoire.",
  "Quelle est la différence entre un juif et un miroir brisé ? Le miroir brisé, ça porte bonheur.",
  "Pourquoi Hitler n'aimait-il pas les puzzles ? Parce qu'il préférait les images complètes.",
  "Comment on appelle un noir qui fait de la facture instrumentale ? Un voleur d'instruments.",
  "Qu'est-ce qui est rouge et qui tourne en rond ? Un bébé dans un sèche-linge.",
  "Comment on fait tenir un bébé dans ta poche arrière ? En galette.",
  "Quelle est la différence entre un juif et un livre de poche ? Le livre de poche, tu peux le mettre dans ta poche.",
  "Pourquoi les handicapés sont-ils comme les cerfs-volants ? Parce que quand le vent s'arrête, ils tombent.",
  "Comment on appelle un noir qui fait de la lutherie ? Un voleur de violons.",
  "Qu'est-ce qui est pire qu'un enfant mort dans une extrudeuse ? Un enfant vivant dans une extrudeuse.",
  "Comment on fait pour qu'un enfant arrête de pleurer ? On lui coupe les cordes vocales.",
  "Quelle est la différence entre un juif et un réveil matin ? Le réveil matin, tu peux le faire taire.",
  "Pourquoi Hitler aimait-il la biologie ? Parce qu'il adorait les expériences génétiques.",
  "Comment on appelle un noir qui fait de la marqueterie ? Un voleur de bois précieux.",
  "Qu'est-ce qui est vert et qui n'a pas de dents ? Un bébé après une bagarre.",
  "Comment on fait tenir tous les bébés dans un tiroir ? En poudre pour bébé.",
  "Quelle est la différence entre un juif et un magazine ? Le magazine, tu peux le jeter.",
  "Pourquoi les bébés sont-ils comme les balles de tennis ? Parce que c'est amusant de les frapper.",
  "Comment on appelle un noir qui fait de la tapisserie ? Un voleur de tissu.",
  "Qu'est-ce qui est pire qu'un enfant mort dans une machine à pâte ? Un enfant vivant dans une machine à pâte.",
  "Comment on fait pour qu'un enfant arrête de grandir ? On le congèle.",
  "Quelle est la différence entre un juif et un livre d'histoire ? Le livre d'histoire, tu peux le refermer.",
  "Pourquoi Hitler n'aimait-il pas les cartes ? Parce qu'il préférait les territoires conquis.",
  "Comment on appelle un noir qui fait de la sculpture sur glace ? Un voleur de glace.",
  "Qu'est-ce qui est rouge et qui fait des bulles ? Un bébé dans un bain d'acide.",
  "Comment on fait tenir un bébé dans ton verre de bière ? En mousse.",
  "Quelle est la différence entre un juif et un jeu de société ? Le jeu de société, tu peux l'arrêter.",
  "Pourquoi les handicapés sont-ils comme les montgolfières ? Parce que quand ils explosent, c'est spectaculaire.",
  "Comment on appelle un noir qui fait de la poterie ? Un voleur d'argile.",
  "Qu'est-ce qui est pire qu'un enfant mort dans un malaxeur ? Un enfant vivant dans un malaxeur.",
  "Comment on fait pour qu'un enfant arrête de sentir ? On le brûle.",
  "Quelle est la différence entre un juif et un livre de coloriage ? Le livre de coloriage, tu peux le colorier.",
  "Pourquoi Hitler aimait-il l'astronomie ? Parce qu'il adorait les étoiles jaunes.",
  "Comment on appelle un noir qui fait de la vannerie ? Un voleur d'osier.",
  "Qu'est-ce qui est vert et qui n'a pas de cheveux ? Un bébé chauve.",
  "Comment on fait tenir tous les juifs dans une boîte ? En cendres.",
  "Quelle est la différence entre un juif et un livre de cuisine ? Le livre de cuisine, tu peux le suivre.",
  "Pourquoi les bébés sont-ils comme les ballons de baudruche ? Parce que c'est amusant de les faire éclater.",
  "Comment on appelle un noir qui fait de la sparterie ? Un voleur de sparterie.",
  "Qu'est-ce qui est pire qu'un enfant mort dans une déchiqueteuse ? Un enfant vivant dans une déchiqueteuse.",
  "Comment on fait pour qu'un enfant arrête de bouger ? On l'enterre.",
  "Quelle est la différence entre un juif et un journal intime ? Le journal intime, tu peux le brûler.",
  "Pourquoi Hitler n'aimait-il pas les devinettes ? Parce qu'il préférait les réponses définitives.",
  "Comment on appelle un noir qui fait de la tabletterie ? Un voleur d'ivoire.",
  "Qu'est-ce qui est rouge et qui tourbillonne ? Un bébé dans un blender.",
  "Comment on fait tenir un bébé dans ton verre à vin ? En sang.",
  "Quelle est la différence entre un juif et un livre de grammaire ? Le livre de grammaire, tu peux le corriger.",
  "Pourquoi les handicapés sont-ils comme les feux tricolores ? Parce que quand ils passent au rouge, tout s'arrête.",
  "Comment on appelle un noir qui fait de la glyptique ? Un voleur de pierres.",
  "Qu'est-ce qui est pire qu'un enfant mort dans un concasseur ? Deux enfants morts dans un concasseur.",
  "Comment on fait pour qu'un enfant arrête de respirer ? On lui met la tête sous l'eau.",
  "Quelle est la différence entre un juif et un livre de mathématiques ? Le livre de mathématiques, tu peux le résoudre.",
  "Pourquoi Hitler aimait-il la musique classique ? Parce qu'il adorait les chambres à gaz en ut majeur.",
  "Comment on appelle un noir qui fait de la facture instrumentale ? Un voleur d'instruments.",
  "Qu'est-ce qui est vert et qui n'a pas de nez ? Un bébé après un accident.",
  "Comment on fait tenir tous les bébés dans une boîte à chaussures ? En poudre.",
  "Quelle est la différence entre un juif et un livre de poésie ? Le livre de poésie, tu peux le lire.",
  "Pourquoi les bébés sont-ils comme les balles de golf ? Parce que c'est amusant de les frapper loin.",
  "Comment on appelle un noir qui fait de la lutherie ? Un voleur de violons.",
  "Qu'est-ce qui est pire qu'un enfant mort dans une presse hydraulique ? Un enfant vivant dans une presse hydraulique.",
  "Comment on fait pour qu'un enfant arrête de crier ? On lui coupe la tête.",
  "Quelle est la différence entre un juif et un livre d'art ? Le livre d'art, tu peux l'admirer.",
  "Pourquoi Hitler n'aimait-il pas les charades ? Parce qu'il préférait les solutions directes.",
  "Comment on appelle un noir qui fait de la marqueterie ? Un voleur de bois.",
  "Qu'est-ce qui est rouge et qui fond ? Un bébé au soleil.",
  "Comment on fait tenir un bébé dans ton verre à cocktail ? En purée.",
  "Quelle est la différence entre un juif et un livre de géographie ? Le livre de géographie, tu peux le consulter.",
  "Pourquoi les handicapés sont-ils comme les cerfs-volants ? Parce que quand le fil casse, ils s'envolent.",
  "Comment on appelle un noir qui fait de la tapisserie ? Un voleur de tissu.",
  "Qu'est-ce qui est pire qu'un enfant mort dans un broyeur à végétaux ? Un enfant vivant dans un broyeur à végétaux.",
  "Comment on fait pour qu'un enfant arrête de grandir ? On le scie en deux.",
  "Quelle est la différence entre un juif et un livre de philosophie ? Le livre de philosophie, tu peux le comprendre.",
  "Pourquoi Hitler aimait-il la chimie organique ? Parce qu'il adorait les expériences avec le carbone.",
  "Comment on appelle un noir qui fait de la sculpture sur glace ? Un voleur de glace.",
  "Qu'est-ce qui est vert et qui n'a pas de bouche ? Un bébé muet.",
  "Comment on fait tenir tous les juifs dans un cendrier ? En cendres.",
  "Quelle est la différence entre un juif et un livre de médecine ? Le livre de médecine, tu peux le suivre.",
  "Pourquoi les bébés sont-ils comme les balles de ping-pong ? Parce que c'est amusant de les faire rebondir.",
  "Comment on appelle un noir qui fait de la sparterie ? Un voleur de sparterie.",
  "Qu'est-ce qui est pire qu'un enfant mort dans une machine à coudre ? Un enfant vivant dans une machine à coudre.",
  "Comment on fait pour qu'un enfant arrête de sentir ? On le met dans un sac.",
  "Quelle est la différence entre un juif et un livre de droit ? Le livre de droit, tu peux le respecter.",
  "Pourquoi Hitler n'aimait-il pas les rébus ? Parce qu'il préférait les images claires.",
  "Comment on appelle un noir qui fait de la tabletterie ? Un voleur d'ivoire.",
  "Qu'est-ce qui est rouge et qui bouillonne ? Un bébé dans une casserole.",
  "Comment on fait tenir un bébé dans ton verre à whisky ? En glace.",
  "Quelle est la différence entre un juif et un livre de linguistique ? Le livre de linguistique, tu peux l'étudier.",
  "Pourquoi les handicapés sont-ils comme les montagnes russes ? Parce que quand ils descendent, tout le monde crie.",
  "Comment on appelle un noir qui fait de la glyptique ? Un voleur de gemmes.",
  "Qu'est-ce qui est pire qu'un enfant mort dans une friteuse ? Un enfant vivant dans une friteuse.",
  "Comment on fait pour qu'un enfant arrête de bouger ? On le cloue au sol.",
  "Quelle est la différence entre un juif et un livre de sociologie ? Le livre de sociologie, tu peux le critiquer.",
  "Pourquoi Hitler aimait-il la physique quantique ? Parce qu'il adorait les particules en mouvement.",
  "Comment on appelle un noir qui fait de la facture instrumentale ? Un voleur d'instruments.",
  "Qu'est-ce qui est vert et qui n'a pas d'yeux ? Un bébé aveugle.",
  "Comment on fait tenir tous les bébés dans une boîte à musique ? En farine.",
  "Quelle est la différence entre un juif et un livre de psychologie ? Le livre de psychologie, tu peux l'analyser.",
  "Pourquoi les bébés sont-ils comme les balles de base-ball ? Parce que c'est amusant de les lancer.",
  "Comment on appelle un noir qui fait de la lutherie ? Un voleur de violons.",
  "Qu'est-ce qui est pire qu'un enfant mort dans une machine à tricoter ? Un enfant vivant dans une machine à tricoter.",
  "Comment on fait pour qu'un enfant arrête de parler ? On lui coupe la langue.",
  "Quelle est la différence entre un juif et un livre de botanique ? Le livre de botanique, tu peux le feuilleter.",
  "Pourquoi Hitler n'aimait-il pas les mots croisés ? Parce qu'il préférait les cases vides.",
  "Comment on appelle un noir qui fait de la marqueterie ? Un voleur de bois.",
  "Qu'est-ce qui est rouge et qui grésille ? Un bébé sur le gril.",
  "Comment on fait tenir un bébé dans ton verre à champagne ? En bulles.",
  "Quelle est la différence entre un juif et un livre de zoologie ? Le livre de zoologie, tu peux le lire.",
  "Pourquoi les handicapés sont-ils comme les cerfs-volants ? Parce que quand ils s'envolent, c'est beau.",
  "Comment on appelle un noir qui fait de la tapisserie ? Un voleur de tissu.",
  "Qu'est-ce qui est pire qu'un enfant mort dans une machine à écrire ? Un enfant vivant dans une machine à écrire.",
  "Comment on fait pour qu'un enfant arrête de sentir ? On le parfume.",
  "Quelle est la différence entre un juif et un livre d'architecture ? Le livre d'architecture, tu peux le suivre.",
  "Pourquoi Hitler aimait-il la géologie ? Parce qu'il adorait les couches terrestres.",
  "Comment on appelle un noir qui fait de la sculpture sur glace ? Un voleur de glace.",
  "Qu'est-ce qui est vert et qui n'a pas de mains ? Un bébé amputé.",
  "Comment on fait tenir tous les juifs dans une allumette ? En étincelle.",
  "Quelle est la différence entre un juif et un livre de chimie ? Le livre de chimie, tu peux l'expérimenter."];

module.exports = {
  name: "blague",
  description: "Affiche une blague aléatoire.",
  run: async (client, message, args) => { 
    const joke = jokes[Math.floor(Math.random() * jokes.length)];
 
    message.channel.send(joke);
  },
};